In [1]:
import re
import html
import warnings
from pathlib import Path

import holidays
import numpy as np
import pandas as pd

import nltk
from nltk.corpus import stopwords
from nltk.corpus import wordnet
from nltk import pos_tag
from nltk.stem import WordNetLemmatizer
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from langdetect import detect, DetectorFactory, LangDetectException

DetectorFactory.seed = 42
warnings.filterwarnings("ignore")
pd.set_option("display.max_colwidth", 120)

# Download resource NLTK yang dibutuhkan (butuh koneksi internet sekali saja)
for pkg in ["stopwords", "wordnet", "omw-1.4", "averaged_perceptron_tagger_eng"]:
    try:
        nltk.download(pkg, quiet=True)
    except Exception as e:
        print(f"Gagal mengunduh '{pkg}': {e}")

In [2]:
news_raw = pd.read_csv('../data/raw/cnbc_with_published.csv')
bi_raw = pd.read_csv('../data/raw/bi-usd-rate.csv')

print("Berita geopolitik :", news_raw.shape)
print("Kurs USD BI       :", bi_raw.shape)
news_raw.head(5)

Berita geopolitik : (16733, 13)
Kurs USD BI       : (1202, 5)

,keyword_matched,title,url,preview_summary,full_text,date_raw,section,published_raw,published_date,published_time,published_timezone,published_iso,scrape_status
0,geopolitical risk,Global shipping authorities warn of maritime trade breakdown amidgeopoliticalturmoil,https://www.cnbc.com/2026/09/08/global-shipping-iran-war-hormuz-rules.html?&qsearchterm=geopolitical risk,Global maritime authorities have warned that the emergence of “parallel systems” threatens to create a two-tier stru...,"Global maritime authorities have warned that the emergence of ""parallel systems"" threatens to create a two-tier stru...",9/8/2026 2:28:41 PM,Markets,2026-09-08T07:28:41+0000,2026-09-08,07:28 AM,0.0,2026-09-08T07:28:41+0000,ok
1,geopolitical risk,Morning Call Sheet: AI rebound meets risinggeopoliticalrisks,https://www.cnbc.com/video/2026/07/31/morning-call-sheet-ai-rebound-meets-rising-geopolitical-risks.html?&qsearchter...,"Peter Tchir, Head of Macro Strategy at Academy Securities, Thomas Martin, Senior Portfolio Manager at GLOBALT Invest...",NaN,7/31/2026 5:58:53 PM,Morning Call,NaN,NaN,NaN,NaN,NaN,not_found
2,geopolitical risk,"Global markets keep shrugging off shocks. Here’s what could break that streak, according to HSBC",https://www.cnbc.com/2026/09/08/global-markets-shrug-off-shocks-hsbc-sees-what-could-break-the-streak.html?&qsearcht...,"Global markets have shrugged off a barrage of shocks in recent years, but HSBC sees several developments that could ...","In this article Global markets have shrugged off a barrage of shocks in recent years, but HSBC sees several developm...",9/8/2026 11:02:43 AM,World Markets,2026-09-08T04:02:43+0000,2026-09-08,04:02 AM,0.0,2026-09-08T04:02:43+0000,ok
3,geopolitical risk,"Yen hovers near seven-month high, dollar steadies",https://www.cnbc.com/2026/09/08/yen-extends-rally-to-new-seven-month-high-dollar-subdued-ahead-of-cpi.html?&qsearcht...,"The Japanese yen hovered near ​a seven-month high on Tuesday, while the dollar was little changed against major peer...","In this article The Japanese yen hovered near ​a seven-month high on Tuesday, while the dollar was little changed ag...",9/8/2026 11:17:07 AM,Currencies,2026-09-08T04:17:07+0000,2026-09-08,04:17 AM,0.0,2026-09-08T04:17:07+0000,ok
4,geopolitical risk,Central banks are bringing gold reserves home asgeopoliticalrisks rise,https://www.cnbc.com/2026/06/17/central-banks-gold-reserves-domestic-storage.html?&qsearchterm=geopolitical risk,"More and more central banks are storing gold bullion at home rather than overseas, as they expect to buy more of the...","In this article More and more central banks are storing gold bullion at home rather than overseas, as they expect to...",6/17/2026 2:28:36 PM,Gold,2026-06-17T07:28:36+0000,2026-06-17,07:28 AM,0.0,2026-06-17T07:28:36+0000,ok

In [3]:
news_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 16733 entries, 0 to 16732
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   keyword_matched     16733 non-null  str
 1   title               16733 non-null  str
 2   url                 16733 non-null  str
 3   preview_summary     16733 non-null  str
 4   full_text           13431 non-null  str
 5   date_raw            16733 non-null  str
 6   section             16649 non-null  str
 7   published_raw       15239 non-null  str
 8   published_date      15239 non-null  str
 9   published_time      15239 non-null  str
 10  published_timezone  15239 non-null  float64
 11  published_iso       15239 non-null  str
 12  scrape_status       16733 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.7 MB

In [4]:
# Parse timestamp mentah GEO dan pisahkan tanggal & jam dengan timezone WIB.
news_raw["date_raw_dt"] = pd.to_datetime(news_raw["date_raw"], errors="coerce")
news_raw["date_raw_dt_wib"] = (
    pd.to_datetime(news_raw["date_raw_dt"], errors="coerce", utc=True)
    .dt.tz_convert("Asia/Jakarta")
    .dt.tz_localize(None)
)
news_raw["tanggal"] = news_raw["date_raw_dt_wib"].dt.strftime("%m/%d/%Y")
news_raw["jam"] = news_raw["date_raw_dt_wib"].dt.strftime("%I:%M %p")
news_raw = news_raw.drop(columns=["date_raw"], errors="ignore")

print("Kolom Berita Geopolitik:")
news_raw[["title", "tanggal", "jam", "date_raw_dt_wib"]].head(5)

Kolom Berita Geopolitik:

,title,tanggal,jam,date_raw_dt_wib
0,Global shipping authorities warn of maritime trade breakdown amidgeopoliticalturmoil,09/08/2026,09:28 PM,2026-09-08 21:28:41
1,Morning Call Sheet: AI rebound meets risinggeopoliticalrisks,08/01/2026,12:58 AM,2026-08-01 00:58:53
2,"Global markets keep shrugging off shocks. Here’s what could break that streak, according to HSBC",09/08/2026,06:02 PM,2026-09-08 18:02:43
3,"Yen hovers near seven-month high, dollar steadies",09/08/2026,06:17 PM,2026-09-08 18:17:07
4,Central banks are bringing gold reserves home asgeopoliticalrisks rise,06/17/2026,09:28 PM,2026-06-17 21:28:36

In [5]:
bi_raw["Tanggal_dt"] = pd.to_datetime(bi_raw["Tanggal"], errors="coerce")
bi_raw["tanggal"] = bi_raw["Tanggal_dt"].dt.strftime("%m/%d/%Y")
bi_raw["jam"] = bi_raw["Tanggal_dt"].dt.strftime("%I:%M %p")
bi_raw = bi_raw.drop(
    columns=["Tanggal"],
    errors="ignore"
)

print("Kolom Kurs BI:")
bi_raw.head(5)

Kolom Kurs BI:

   NO  Nilai  Kurs Jual  Kurs Beli Tanggal_dt     tanggal       jam
0   1      1   17834.73   17657.27 2026-09-01  09/01/2026  12:00 AM
1   2      1   17791.51   17614.49 2026-08-31  08/31/2026  12:00 AM
2   3      1   17850.81   17673.19 2026-08-28  08/28/2026  12:00 AM
3   4      1   17805.58   17628.42 2026-08-27  08/27/2026  12:00 AM
4   5      1   17791.51   17614.49 2026-08-26  08/26/2026  12:00 AM

# Data Cleaning

## 1. Filter Dataset

In [6]:
#delete duplicate rows
def word_count(text):
    if not isinstance(text, str):
        return 0
    return len(text.split())

news = news_raw.copy()
# Ukuran data awal
print(f"Baris awal                         : {len(news_raw)}")

# Filter rentang tanggal inklusif: 1 September 2021 - 1 September 2026
start_date = pd.Timestamp("2021-09-01")
end_date = pd.Timestamp("2026-09-01 23:59:59")
news = news[news["date_raw_dt"].between(start_date, end_date, inclusive="both")]
print(f"Setelah filter rentang 1 September 2021 - 1 September 2026 : {len(news)}")

# Setelah di drop URL
news = news.drop_duplicates(subset=["url"], keep="first")
print(f"Setelah dedup url                  : {len(news)}")

# Setelah di drop title + date_raw
news = news.drop_duplicates(subset=["title", "tanggal", "jam"], keep="first")
print(f"Setelah dedup title+date_raw       : {len(news)}")

Baris awal                         : 16733
Setelah filter rentang 1 September 2021 - 1 September 2026 : 8871
Setelah dedup url                  : 8871
Setelah dedup title+date_raw       : 7084

In [7]:
# Filter full_text yang kosong

# Buang baris yang tidak memiliki isi teks pada ketiga sumber konten.
text_columns = ["title", "preview_summary", "full_text"]
text_content = news[text_columns].fillna("").astype(str).agg(" ".join, axis=1).str.strip()
mask_empty = text_content.eq("")
news = news.loc[~mask_empty].copy()
print(f"Setelah drop teks kosong             : {len(news)}")

# Buang item multimedia berdasarkan URL, judul, dan section.
non_article_pattern = r"\b(video|videos|image|images|photo|photos|foto|gambar|audio|podcast|gallery|galeri|live)\b|\.(mp4|mov|avi|mp3|wav|jpg|jpeg|png)(?:$|[?#])"
content_metadata = news[["url", "title", "section"]].fillna("").astype(str).agg(" ".join, axis=1)
mask_non_article = content_metadata.str.contains(non_article_pattern, case=False, regex=True, na=False)
news = news.loc[~mask_non_article].copy()
print(f"Setelah drop video/gambar/audio      : {len(news)}")

news.head(5)

Setelah drop teks kosong             : 7084
Setelah drop video/gambar/audio      : 6214

,keyword_matched,title,url,preview_summary,full_text,section,published_raw,published_date,published_time,published_timezone,published_iso,scrape_status,date_raw_dt,date_raw_dt_wib,tanggal,jam
4,geopolitical risk,Central banks are bringing gold reserves home asgeopoliticalrisks rise,https://www.cnbc.com/2026/06/17/central-banks-gold-reserves-domestic-storage.html?&qsearchterm=geopolitical risk,"More and more central banks are storing gold bullion at home rather than overseas, as they expect to buy more of the...","In this article More and more central banks are storing gold bullion at home rather than overseas, as they expect to...",Gold,2026-06-17T07:28:36+0000,2026-06-17,07:28 AM,0.0,2026-06-17T07:28:36+0000,ok,2026-06-17 14:28:36,2026-06-17 21:28:36,06/17/2026,09:28 PM
8,geopolitical risk,Oil rises 2% as White House says no US-Iran talks happening,https://www.cnbc.com/2026/08/27/oil-prices-extend-losses-on-expectations-talks-to-ease-middle-east-supply-woes.html?...,"Oil prices rose Thursday, after Washington confirmed it was not in talks with ‌Iran despite diplomatic efforts by ot...","In this article Oil prices rose Thursday, after Washington confirmed it was not in talks with ‌Iran despite diplomat...",Oil,2026-08-27T02:49:03+0000,2026-08-27,02:49 AM,0.0,2026-08-27T02:49:03+0000,ok,2026-08-27 09:49:03,2026-08-27 16:49:03,08/27/2026,04:49 PM
9,geopolitical risk,Jamie Dimon says markets underestimate risks and he wouldn’t buy stocks or Treasurys at current ...,https://www.cnbc.com/2026/07/21/jpmorgan-chase-ceo-jamie-dimon-market-risk.html?&qsearchterm=geopolitical risk,JPMorgan Chase CEO Jamie Dimon said investors are underestimating the risks facing the global economy and that he wo...,In this article JPMorgan ChaseCEOJamie Dimonsaid investors are underestimating the risks facing the global economy a...,Finance,2026-07-20T23:01:01+0000,2026-07-20,11:01 PM,0.0,2026-07-20T23:01:01+0000,ok,2026-07-21 06:01:01,2026-07-21 13:01:01,07/21/2026,01:01 PM
13,geopolitical risk,"Citi Wealth warns markets may be ‘uncomfortably strong’ amid mountinggeopolitical, inflation risks",https://www.cnbc.com/2026/05/18/citi-wealth-warns-markets-may-be-uncomfortably-strong-as-risks-mount.html?&qsearchte...,"Global markets may be due for a period of consolidation after a sharp rally in equities, even as the longer-term out...",NaN,Pro: Analysis,2026-05-18T05:37:18+0000,2026-05-18,05:37 AM,0.0,2026-05-18T05:37:18+0000,ok,2026-05-18 12:37:18,2026-05-18 19:37:18,05/18/2026,07:37 PM
15,geopolitical risk,Where fixed income investors are finding yield asgeopoliticalriskrattles markets,https://www.cnbc.com/2026/04/10/where-fixed-income-investors-are-finding-yield-as-geopolitical-risk-rattles-markets....,"As the Iran war shakes up markets, strategists say there are still plenty of sources of relatively safe yield for in...",NaN,Pro: Income Investing,2026-04-10T19:25:17+0000,2026-04-10,07:25 PM,0.0,2026-04-10T19:25:17+0000,ok,2026-04-11 02:25:17,2026-04-11 09:25:17,04/11/2026,09:25 AM

In [8]:
# Panjang text minimal 350

effective_text = news["full_text"].fillna(news["preview_summary"])
news = news.loc[effective_text.apply(word_count) >= 350]
print(f"Setelah filter panjang teks min     : {len(news)}")

Setelah filter panjang teks min     : 4349

In [9]:
#Filter keyword yang relevan dengan geopolitik dan ekonomi
RELEVANCE_KEYWORDS = [
    "geopolitics",
    "geopolitical risk",
    "geopolitical tensions",
    "geopolitical fragmentation",
    "armed conflict",
    "global conflict",
    "international conflict",
    "military tensions",
    "national security",
    "sanctions",
    "trade war",
    "tariffs",
    "embargo",
    "export controls",
    "protectionism",
    "supply chain disruption",
    "diplomacy",
    "foreign policy",
    "nato",
    "brics",
    "opec",
    "g7",
]

EXCLUDE_SECTIONS = [
    "sports", "entertainment", "television", "lifestyle", "travel",
    "food retail", "beer, wine & spirits", "college", "modern medicine",
    "life changes", "fashion", "celebrity",
]

def is_relevant(row):
    """Berita dianggap relevan jika keyword_matched terisi ATAU teks memuat
    salah satu kata kunci geopolitik/ekonomi pada RELEVANCE_KEYWORDS."""
    if isinstance(row["keyword_matched"], str) and row["keyword_matched"].strip():
        return True
    haystack = f"{row.get('title', '')} {row.get('preview_summary', '')}".lower()
    return any(kw in haystack for kw in RELEVANCE_KEYWORDS)

mask_relevant = news.apply(is_relevant, axis=1)
news = news.loc[mask_relevant]

print(f"Setelah filter relevansi kata kunci : {len(news)}")

# 4.5 Filter kategori/section yang tidak relevan
section_lower = news["section"].fillna("").str.lower()
mask_section = ~section_lower.isin(EXCLUDE_SECTIONS)
news = news.loc[mask_section].reset_index(drop=True)

print(f"Setelah filter kategori/section     : {len(news)}")

news.head(3)

Setelah filter relevansi kata kunci : 4349
Setelah filter kategori/section     : 4336

,keyword_matched,title,url,preview_summary,full_text,section,published_raw,published_date,published_time,published_timezone,published_iso,scrape_status,date_raw_dt,date_raw_dt_wib,tanggal,jam
0,geopolitical risk,Central banks are bringing gold reserves home asgeopoliticalrisks rise,https://www.cnbc.com/2026/06/17/central-banks-gold-reserves-domestic-storage.html?&qsearchterm=geopolitical risk,"More and more central banks are storing gold bullion at home rather than overseas, as they expect to buy more of the...","In this article More and more central banks are storing gold bullion at home rather than overseas, as they expect to...",Gold,2026-06-17T07:28:36+0000,2026-06-17,07:28 AM,0.0,2026-06-17T07:28:36+0000,ok,2026-06-17 14:28:36,2026-06-17 21:28:36,06/17/2026,09:28 PM
1,geopolitical risk,Oil rises 2% as White House says no US-Iran talks happening,https://www.cnbc.com/2026/08/27/oil-prices-extend-losses-on-expectations-talks-to-ease-middle-east-supply-woes.html?...,"Oil prices rose Thursday, after Washington confirmed it was not in talks with ‌Iran despite diplomatic efforts by ot...","In this article Oil prices rose Thursday, after Washington confirmed it was not in talks with ‌Iran despite diplomat...",Oil,2026-08-27T02:49:03+0000,2026-08-27,02:49 AM,0.0,2026-08-27T02:49:03+0000,ok,2026-08-27 09:49:03,2026-08-27 16:49:03,08/27/2026,04:49 PM
2,geopolitical risk,Jamie Dimon says markets underestimate risks and he wouldn’t buy stocks or Treasurys at current ...,https://www.cnbc.com/2026/07/21/jpmorgan-chase-ceo-jamie-dimon-market-risk.html?&qsearchterm=geopolitical risk,JPMorgan Chase CEO Jamie Dimon said investors are underestimating the risks facing the global economy and that he wo...,In this article JPMorgan ChaseCEOJamie Dimonsaid investors are underestimating the risks facing the global economy a...,Finance,2026-07-20T23:01:01+0000,2026-07-20,11:01 PM,0.0,2026-07-20T23:01:01+0000,ok,2026-07-21 06:01:01,2026-07-21 13:01:01,07/21/2026,01:01 PM

In [10]:
# delete missing values
jumlah_nan = news["full_text"].isna().sum()

print("Jumlah full_text NaN:", jumlah_nan)

news_nan = news.loc[news["full_text"].isna()]

news_nan[
    ["url", "title", "preview_summary", "full_text"]
].head()

news = news.dropna(subset=["full_text"]).reset_index(drop=True)

print("Jumlah baris setelah drop NaN:", len(news))
print("Sisa NaN pada full_text:", news["full_text"].isna().sum())

Jumlah full_text NaN: 0
Jumlah baris setelah drop NaN: 4336
Sisa NaN pada full_text: 0

## 2. Cleaning Data News

In [11]:
#menggabungkan title, preview, dan full_text

# Tidak ada nilai kosong yang mengganggu penggabungan teks.
news[["title", "preview_summary", "full_text"]] = (
    news[["title", "preview_summary", "full_text"]].fillna("")
)

# Gabungkan title + preview_summary + full_text.
news["combined_raw"] = (
    ((news["title"] + " ") * 2)
    + news["preview_summary"] + " "
    + news["full_text"]
)

print(f"Jumlah baris: {len(news)}")
news[["title", "combined_raw"]].head(3)

Jumlah baris: 4336

,title,combined_raw
0,Central banks are bringing gold reserves home asgeopoliticalrisks rise,Central banks are bringing gold reserves home asgeopoliticalrisks rise Central banks are bringing gold reserves home...
1,Oil rises 2% as White House says no US-Iran talks happening,Oil rises 2% as White House says no US-Iran talks happening Oil rises 2% as White House says no US-Iran talks happen...
2,Jamie Dimon says markets underestimate risks and he wouldn’t buy stocks or Treasurys at current ...,Jamie Dimon says markets underestimate risks and he wouldn’t buy stocks or Treasurys at current ... Jamie Dimon says...

In [12]:
import unicodedata
from collections import Counter

symbol_counter = Counter()
for text in news["combined_raw"]:
    for ch in text:
        if not (ch.isalnum() or ch.isspace()):
            symbol_counter[ch] += 1

symbol_df = pd.DataFrame(
    [
        (ch, unicodedata.name(ch, "UNKNOWN"), count)
        for ch, count in symbol_counter.most_common()
    ],
    columns=["simbol", "nama_unicode", "jumlah"],
)

print(f"Jumlah jenis simbol unik pada combined_raw: {len(symbol_df)}")
symbol_df

Jumlah jenis simbol unik pada combined_raw: 54

   simbol                                nama_unicode  jumlah
0       .                                   FULL STOP  232989
1       ,                                       COMMA  203423
2       "                              QUOTATION MARK   88912
3       '                                  APOSTROPHE   60351
4       -                                HYPHEN-MINUS   41818
5       %                                PERCENT SIGN   18915
6       —                                     EM DASH   10379
7       $                                 DOLLAR SIGN    9806
8       ’                 RIGHT SINGLE QUOTATION MARK    6782
9       :                                       COLON    5100
10      )                           RIGHT PARENTHESIS    3958
11      (                            LEFT PARENTHESIS    3943
12      [                         LEFT SQUARE BRACKET    1926
13      ]                        RIGHT SQUARE BRACKET    1926
14      ?                               QUESTION MARK    1644
15      &                                   AMPERSAND    1589
16      ‘                  LEFT SINGLE QUOTATION MARK    1457
17      –                                     EN DASH    1184
18      ​                            ZERO WIDTH SPACE     859
19      ;                                   SEMICOLON     850
20      +                                   PLUS SIGN     766
21      “                  LEFT DOUBLE QUOTATION MARK     648
22      ⁠                                 WORD JOINER     644
23      /                                     SOLIDUS     636
24      ‌                       ZERO WIDTH NON-JOINER     503
25      ”                 RIGHT DOUBLE QUOTATION MARK     500
26      …                         HORIZONTAL ELLIPSIS     438
27      !                            EXCLAMATION MARK     279
28      £                                  POUND SIGN     160
29      ‑                         NON-BREAKING HYPHEN     115
30      ‍                           ZERO WIDTH JOINER      71
31      *                                    ASTERISK      52
32      #                                 NUMBER SIGN      45
33      @                               COMMERCIAL AT      40
34      →                            RIGHTWARDS ARROW      35
35      ′                                       PRIME      26
36      |                               VERTICAL LINE      22
37      ~                                       TILDE      20
38      ″                                DOUBLE PRIME      18
39      €                                   EURO SIGN      10
40      `                                GRAVE ACCENT       9
41      »  RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK       7
42      _                                    LOW LINE       7
43      =                                 EQUALS SIGN       6
44      °                                 DEGREE SIGN       4
45      •                                      BULLET       3
46      <                              LESS-THAN SIGN       2
47      ‐                                      HYPHEN       2
48      ­                                 SOFT HYPHEN       2
49      ，                             FULLWIDTH COMMA       1
50      }                         RIGHT CURLY BRACKET       1
51      ﻿                   ZERO WIDTH NO-BREAK SPACE       1
52      >                           GREATER-THAN SIGN       1
53      ™                             TRADE MARK SIGN       1

In [13]:
#cleaning dari tanda baca yang tidak berguna

URL_RE = re.compile(r"http\S+|www\.\S+")
EMAIL_RE = re.compile(r"\S+@\S+\.\S+")
HTML_TAG_RE = re.compile(r"<[^>]+>")
EMOJI_RE = re.compile(
    "["
    "\U0001F300-\U0001FAFF"
    "\U00002700-\U000027BF"
    "\U0001F1E6-\U0001F1FF"
    "\U00002600-\U000026FF"
    "]+",
    flags=re.UNICODE,
)

# Hanya simbol mata uang yang diubah jadi kata.
# Simbol lain (&, +, tanda baca umum) dibuang di NON_ALNUM_RE.
CURRENCY_WORDS = {
    "%": "percent",
    "$": "dollar",
    "£": "pound",
    "€": "euro",
    "¥": "yen",
}
CURRENCY_RE = re.compile("|".join(re.escape(sym) for sym in CURRENCY_WORDS))
NON_ALNUM_RE = re.compile(r"[^a-zA-Z0-9\s]")  # simbol/tanda baca sisa dibuang; huruf & angka dipertahankan
MULTI_SPACE_RE = re.compile(r"\s+")


def normalize_text(text: str) -> str:
    """Hapus HTML/URL/email/emoji, ubah simbol mata uang jadi kata, angka dipertahankan."""
    if not isinstance(text, str) or not text.strip():
        return ""
    t = html.unescape(text)
    t = HTML_TAG_RE.sub(" ", t)
    t = URL_RE.sub(" ", t)
    t = EMAIL_RE.sub(" ", t)
    t = EMOJI_RE.sub(" ", t)
    t = CURRENCY_RE.sub(lambda m: f" {CURRENCY_WORDS[m.group(0)]} ", t)
    t = NON_ALNUM_RE.sub(" ", t)
    t = MULTI_SPACE_RE.sub(" ", t).strip()
    return t


news["normalized_text"] = news["combined_raw"].apply(normalize_text)

news[["combined_raw", "normalized_text"]].head(3)

,combined_raw,normalized_text
0,Central banks are bringing gold reserves home asgeopoliticalrisks rise Central banks are bringing gold reserves home...,Central banks are bringing gold reserves home asgeopoliticalrisks rise Central banks are bringing gold reserves home...
1,Oil rises 2% as White House says no US-Iran talks happening Oil rises 2% as White House says no US-Iran talks happen...,Oil rises 2 percent as White House says no US Iran talks happening Oil rises 2 percent as White House says no US Ira...
2,Jamie Dimon says markets underestimate risks and he wouldn’t buy stocks or Treasurys at current ... Jamie Dimon says...,Jamie Dimon says markets underestimate risks and he wouldn t buy stocks or Treasurys at current Jamie Dimon says mar...

In [14]:
# lowercasing
news["lower_text"] = news["normalized_text"].str.lower()

news[["normalized_text", "lower_text"]].head(3)

,normalized_text,lower_text
0,Central banks are bringing gold reserves home asgeopoliticalrisks rise Central banks are bringing gold reserves home...,central banks are bringing gold reserves home asgeopoliticalrisks rise central banks are bringing gold reserves home...
1,Oil rises 2 percent as White House says no US Iran talks happening Oil rises 2 percent as White House says no US Ira...,oil rises 2 percent as white house says no us iran talks happening oil rises 2 percent as white house says no us ira...
2,Jamie Dimon says markets underestimate risks and he wouldn t buy stocks or Treasurys at current Jamie Dimon says mar...,jamie dimon says markets underestimate risks and he wouldn t buy stocks or treasurys at current jamie dimon says mar...

In [15]:
#memastikan bahasanya english semua
def detect_language(text: str) -> str:
    if not isinstance(text, str) or len(text.strip()) < 20:
        return "unknown"
    try:
        return detect(text)
    except LangDetectException:
        return "unknown"


news["detected_lang"] = news["lower_text"].apply(detect_language)

print("Distribusi bahasa terdeteksi:")
print(news["detected_lang"].value_counts().head(10))

baris_sebelum = len(news)
news = news.loc[news["detected_lang"] == "en"].reset_index(drop=True)
print(f"\nSetelah filter bahasa Inggris (en) : {len(news)} (dibuang {baris_sebelum - len(news)} baris)")

news[["lower_text", "detected_lang"]].head(3)

Distribusi bahasa terdeteksi:
detected_lang
en    4336
Name: count, dtype: int64

Setelah filter bahasa Inggris (en) : 4336 (dibuang 0 baris)

,lower_text,detected_lang
0,central banks are bringing gold reserves home asgeopoliticalrisks rise central banks are bringing gold reserves home...,en
1,oil rises 2 percent as white house says no us iran talks happening oil rises 2 percent as white house says no us ira...,en
2,jamie dimon says markets underestimate risks and he wouldn t buy stocks or treasurys at current jamie dimon says mar...,en

## 3. Cleaning Data Kurs

In [16]:
# Gabungkan tanggal dan jam untuk satu kolom datetime kanonik.
bi_raw["Tanggal"] = pd.to_datetime(
    bi_raw["tanggal"].astype(str).str.strip() + " " + bi_raw["jam"].astype(str).str.strip(),
    format="%m/%d/%Y %I:%M %p",
    errors="coerce",
)

print(bi_raw.shape)
bi_raw.head(3)

(1202, 8)

   NO  Nilai  Kurs Jual  Kurs Beli Tanggal_dt     tanggal       jam    Tanggal
0   1      1   17834.73   17657.27 2026-09-01  09/01/2026  12:00 AM 2026-09-01
1   2      1   17791.51   17614.49 2026-08-31  08/31/2026  12:00 AM 2026-08-31
2   3      1   17850.81   17673.19 2026-08-28  08/28/2026  12:00 AM 2026-08-28

In [17]:
def clean_numeric(series: pd.Series) -> pd.Series:
    """Hapus pemisah ribuan dan konversi nilai ke float."""
    cleaned = series.astype(str).str.replace(",", "", regex=False).str.strip()
    return pd.to_numeric(cleaned, errors="coerce")



bi_raw["Kurs Jual"] = clean_numeric(bi_raw["Kurs Jual"])
bi_raw["Kurs Beli"] = clean_numeric(bi_raw["Kurs Beli"])
bi_raw["NO"] = pd.to_numeric(bi_raw["NO"], errors="coerce")
bi_raw["Nilai"] = pd.to_numeric(bi_raw["Nilai"], errors="coerce")

print(f"Baris awal BI                 : {len(bi_raw)}")

# Pertahankan hanya rentang 1 September 2021 sampai 1 September 2026.
bi = bi_raw.loc[bi_raw["Tanggal"].between(start_date, end_date, inclusive="both")]
print(f"Setelah filter rentang tanggal: {len(bi)}")

mask_valid_numeric = (
    bi["Kurs Jual"].notna()
    & bi["Kurs Beli"].notna()
    & (bi["Kurs Jual"] > 0)
    & (bi["Kurs Beli"] > 0)
)
bi = bi.loc[mask_valid_numeric]
print(f"Setelah filter numerik valid  : {len(bi)}")

mask_valid_spread = bi["Kurs Jual"] > bi["Kurs Beli"]
bi = bi.loc[mask_valid_spread]
print(f"Setelah filter Jual > Beli    : {len(bi)}")

bi = (
    bi.sort_values("Tanggal")
    .drop_duplicates(subset=["Tanggal"], keep="last")
    .reset_index(drop=True)
)
print(f"Setelah dedup tanggal         : {len(bi)}")

bi.head(3)

Baris awal BI                 : 1202
Setelah filter rentang tanggal: 1202
Setelah filter numerik valid  : 1202
Setelah filter Jual > Beli    : 1202
Setelah dedup tanggal         : 1202

,NO,Nilai,Kurs Jual,Kurs Beli,Tanggal_dt,tanggal,jam,Tanggal
0,1202,1,14377.53,14234.47,2021-09-01,09/01/2021,12:00 AM,2021-09-01
1,1201,1,14355.42,14212.58,2021-09-02,09/02/2021,12:00 AM,2021-09-02
2,1200,1,14352.41,14209.60,2021-09-03,09/03/2021,12:00 AM,2021-09-03

# Preprocessing

In [18]:
#stopword removal
CUSTOM_STOPWORDS = {
    "cnbc", "article", "read", "also", "said", "says", "say",
    "would", "could", "also", "one", "two", "get", "got",
}
STOPWORDS_EN = set(stopwords.words("english")) | CUSTOM_STOPWORDS


def remove_stopwords(text: str) -> list:
    # Tokenisasi split-spasi lalu buang stopword Bahasa Inggris & token 1 karakter.
    if not isinstance(text, str) or not text.strip():
        return []
    tokens = text.split()
    return [tok for tok in tokens if tok not in STOPWORDS_EN and len(tok) > 1]


news["tokens_no_stopwords"] = news["lower_text"].apply(remove_stopwords)
news["text_no_stopwords"] = news["tokens_no_stopwords"].apply(" ".join)

avg_before = news["lower_text"].apply(word_count).mean()
avg_after = news["tokens_no_stopwords"].apply(len).mean()
print(f"Rata-rata jumlah kata sebelum stopword removal : {avg_before:.1f}")
print(f"Rata-rata jumlah kata sesudah stopword removal  : {avg_after:.1f}")

news[["lower_text", "text_no_stopwords"]].head(3)

Rata-rata jumlah kata sebelum stopword removal : 862.4
Rata-rata jumlah kata sesudah stopword removal  : 494.5

,lower_text,text_no_stopwords
0,central banks are bringing gold reserves home asgeopoliticalrisks rise central banks are bringing gold reserves home...,central banks bringing gold reserves home asgeopoliticalrisks rise central banks bringing gold reserves home asgeopo...
1,oil rises 2 percent as white house says no us iran talks happening oil rises 2 percent as white house says no us ira...,oil rises percent white house us iran talks happening oil rises percent white house us iran talks happening oil pric...
2,jamie dimon says markets underestimate risks and he wouldn t buy stocks or treasurys at current jamie dimon says mar...,jamie dimon markets underestimate risks buy stocks treasurys current jamie dimon markets underestimate risks buy sto...

In [19]:
#lemmatization (POS aware)
lemmatizer = WordNetLemmatizer()

POS_MAP = {
    "J": wordnet.ADJ,
    "V": wordnet.VERB,
    "N": wordnet.NOUN,
    "R": wordnet.ADV,
}


def get_wordnet_pos(treebank_tag: str) -> str:
    # Tag POS Penn Treebank (huruf pertama) ke format POS WordNet; default kata benda.
    return POS_MAP.get(treebank_tag[0], wordnet.NOUN)


def lemmatize_tokens(tokens: list) -> list:
    # Lemmatisasi tiap token berdasarkan POS tag-nya (POS-aware lemmatization).
    if not tokens:
        return []
    tagged_tokens = pos_tag(tokens)
    return [
        lemmatizer.lemmatize(token, pos=get_wordnet_pos(tag))
        for token, tag in tagged_tokens
    ]


news["tokens_lemmatized"] = news["tokens_no_stopwords"].apply(lemmatize_tokens)
news["text_lemmatized"] = news["tokens_lemmatized"].apply(" ".join)

news[["text_no_stopwords", "text_lemmatized"]].head(3)

,text_no_stopwords,text_lemmatized
0,central banks bringing gold reserves home asgeopoliticalrisks rise central banks bringing gold reserves home asgeopo...,central bank bring gold reserve home asgeopoliticalrisks rise central bank bring gold reserve home asgeopoliticalris...
1,oil rises percent white house us iran talks happening oil rises percent white house us iran talks happening oil pric...,oil rise percent white house u iran talk happen oil rise percent white house u iran talk happen oil price rise thurs...
2,jamie dimon markets underestimate risks buy stocks treasurys current jamie dimon markets underestimate risks buy sto...,jamie dimon market underestimate risk buy stock treasurys current jamie dimon market underestimate risk buy stock tr...

# Penyelarasan Data

In [20]:
#change timezone to WIB
news['published_raw'] = pd.to_datetime(news['published_raw'], errors='coerce', utc=True)
news['published_raw'] = news['published_raw'].dt.tz_convert('Asia/Jakarta')

#pisahin tanggal & waktu
news['date'] = news['published_raw'].dt.date
news['time'] = news['published_raw'].dt.time

In [21]:
#change timezone to WIB
news['published_raw'] = pd.to_datetime(news['published_raw'], errors='coerce', utc=True)
news['published_raw'] = news['published_raw'].dt.tz_convert('Asia/Jakarta')

#pisahin tanggal & waktu
news['date'] = news['published_raw'].dt.date
news['time'] = news['published_raw'].dt.time

In [22]:
def align_to_trading_date(dt):
    # Step 1: kalau lewat cutoff 15:15:00, geser ke hari berikutnya
    cutoff = dt.replace(hour=15, minute=0, second=0, microsecond=0)
    if dt > cutoff:
        dt = dt + pd.Timedelta(days=1)

    # Step 2: kalau hasilnya jatuh di weekend, geser ke Senin
    if dt.weekday() == 5:      # Sabtu
        dt = dt + pd.Timedelta(days=2)
    elif dt.weekday() == 6:    # Minggu
        dt = dt + pd.Timedelta(days=1)

    return dt.normalize()  # buang jam, sisakan tanggal saja

news['aligned_trading_date'] = news['date_raw_dt'].apply(align_to_trading_date)
news

,keyword_matched,title,url,preview_summary,full_text,section,published_raw,published_date,published_time,published_timezone,...,normalized_text,lower_text,detected_lang,tokens_no_stopwords,text_no_stopwords,tokens_lemmatized,text_lemmatized,date,time,aligned_trading_date
0,geopolitical risk,Central banks are bringing gold reserves home asgeopoliticalrisks rise,https://www.cnbc.com/2026/06/17/central-banks-gold-reserves-domestic-storage.html?&qsearchterm=geopolitical risk,"More and more central banks are storing gold bullion at home rather than overseas, as they expect to buy more of the...","In this article More and more central banks are storing gold bullion at home rather than overseas, as they expect to...",Gold,2026-06-17 14:28:36+07:00,2026-06-17,07:28 AM,0.0,...,Central banks are bringing gold reserves home asgeopoliticalrisks rise Central banks are bringing gold reserves home...,central banks are bringing gold reserves home asgeopoliticalrisks rise central banks are bringing gold reserves home...,en,"[central, banks, bringing, gold, reserves, home, asgeopoliticalrisks, rise, central, banks, bringing, gold, reserves...",central banks bringing gold reserves home asgeopoliticalrisks rise central banks bringing gold reserves home asgeopo...,"[central, bank, bring, gold, reserve, home, asgeopoliticalrisks, rise, central, bank, bring, gold, reserve, home, as...",central bank bring gold reserve home asgeopoliticalrisks rise central bank bring gold reserve home asgeopoliticalris...,2026-06-17,14:28:36,2026-06-17
1,geopolitical risk,Oil rises 2% as White House says no US-Iran talks happening,https://www.cnbc.com/2026/08/27/oil-prices-extend-losses-on-expectations-talks-to-ease-middle-east-supply-woes.html?...,"Oil prices rose Thursday, after Washington confirmed it was not in talks with ‌Iran despite diplomatic efforts by ot...","In this article Oil prices rose Thursday, after Washington confirmed it was not in talks with ‌Iran despite diplomat...",Oil,2026-08-27 09:49:03+07:00,2026-08-27,02:49 AM,0.0,...,Oil rises 2 percent as White House says no US Iran talks happening Oil rises 2 percent as White House says no US Ira...,oil rises 2 percent as white house says no us iran talks happening oil rises 2 percent as white house says no us ira...,en,"[oil, rises, percent, white, house, us, iran, talks, happening, oil, rises, percent, white, house, us, iran, talks, ...",oil rises percent white house us iran talks happening oil rises percent white house us iran talks happening oil pric...,"[oil, rise, percent, white, house, u, iran, talk, happen, oil, rise, percent, white, house, u, iran, talk, happen, o...",oil rise percent white house u iran talk happen oil rise percent white house u iran talk happen oil price rise thurs...,2026-08-27,09:49:03,2026-08-27
2,geopolitical risk,Jamie Dimon says markets underestimate risks and he wouldn’t buy stocks or Treasurys at current ...,https://www.cnbc.com/2026/07/21/jpmorgan-chase-ceo-jamie-dimon-market-risk.html?&qsearchterm=geopolitical risk,JPMorgan Chase CEO Jamie Dimon said investors are underestimating the risks facing the global economy and that he wo...,In this article JPMorgan ChaseCEOJamie Dimonsaid investors are underestimating the risks facing the global economy a...,Finance,2026-07-21 06:01:01+07:00,2026-07-20,11:01 PM,0.0,...,Jamie Dimon says markets underestimate risks and he wouldn t buy stocks or Treasurys at current Jamie Dimon says mar...,jamie dimon says markets underestimate risks and he wouldn t buy stocks or treasurys at current jamie dimon says mar...,en,"[jamie, dimon, markets, underestimate, risks, buy, stocks, treasurys, current, jamie, dimon, markets, underestimate,...",jamie dimon markets underestimate risks buy stocks treasurys current jamie dimon markets underestimate risks buy sto...,"[jamie, dimon, market, underestimate, risk, buy, stock, treasurys, current, jamie, dimon, market, underestimate, ris...",jamie dimon market underestimate risk buy stock treasurys current jamie dimon market underestimate risk buy stock tr...,2026-07-21,06:01:01,2026-07-21
3,geopolitical risk,China’s super-rich fled Singapore. Now they want to come back,https://www.cnbc.com/2026/08/28/chinas-super-rich-fled-singapore-now-they-want-to-come-back.html?&qsearchterm=geopol...,"A year ago, wealthy Chinese families were souring on Singapore. Its rules felt onerous, its nightlife subdued. Other...","A year ago, wealthy Chinese familieswere souring on Singapore. Its rules felt onerous, its nightlife subdued. Other ...",Wealth,2026-08-28 06:29:56+07:00,2026-08-27,11:29 PM,0.0,...,China s super rich fled Singapore Now they want to come back China s super rich fled Singapore Now they want to come...,china s super rich fled singapore now they want to come back china s super rich fled singapore now they want to come...,en,"[china, super, rich, fled, singapore, want, come, back, china, super, rich, fled, singapore, want, come, back, year,...",china super rich fled singapore want come back china super rich fled singapore want come back year ago wealthy chine...,"[china, super, rich, flee, singapore, want, come, back, china, super, rich, flee, singapore, want, come, back, year,...",china super rich flee singapore want come back china super rich flee singapore want come back year ago wealthy chine...,2026-08-28,06:29:56,2026-08-28
4,geopolitical risk,‘Don’t get too comfortable’: Wall Street’s ‘fear gauge’ hits 2026 low — here’s why it’s ...,https://www.cnbc.com/2026/08/17/stock-market-volatility-vix-wall-street.html?&qsearchterm=geopolitical risk,"Wall Street’s so-called “fear gauge” has fallen to its lowest level of 2026 so far, reflecting relative market tranq...","Wall Street's so-called ""fear gauge"" has fallen to its lowest level of 2026 so far, reflecting relative market tranq...",Markets,2026-08-17 19:19:50+07:00,2026-08-17,12:19 PM,0.0,...,Don t get too comfortable Wall Street s fear gauge hits 2026 low here s why it s Don t get too comfortable Wall Stre...,don t get too comfortable wall street s fear gauge hits 2026 low here s why it s don t get too comfortable wall stre...,en,"[comfortable, wall, street, fear, gauge, hits, 2026, low, comfortable, wall, street, fear, gauge, hits, 2026, low, w...",comfortable wall street fear gauge hits 2026 low comfortable wall street fear gauge hits 2026 low wall street called...,"[comfortable, wall, street, fear, gauge, hit, 2026, low, comfortable, wall, street, fear, gauge, hit, 2026, low, wal...",comfortable wall street fear gauge hit 2026 low comfortable wall street fear gauge hit 2026 low wall street call fea...,2026-08-17,19:19:50,2026-08-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4331,diplomacy,‘Dark day for Europe’: World leaders condemn Russia’s invasion of Ukraine,https://www.cnbc.com/2022/02/24/leaders-of-us-uk-eu-and-canada-condemn-russian-invasion-on-ukraine.html?&qsearchterm...,World leaders condemned Russia’s invasion of Ukraine after President Vladimir Putin declared the start of a military...,World leaders condemnedRussia's invasion of Ukraineafter President Vladimir Putin declared the start of a military o...,World Politics,2022-02-24 16:37:42+07:00,2022-02-24,09:37 AM,0.0,...,Dark day for Europe World leaders condemn Russia s invasion of Ukraine Dark day for Europe World leaders condemn Rus...,dark day for europe world leaders condemn russia s invasion of ukraine dark day for europe world leaders condemn rus...,en,"[dark, day, europe, world, leaders, condemn, russia, invasion, ukraine, dark, day, europe, world, leaders, condemn, ...",dark day europe world leaders condemn russia invasion ukraine dark day europe world leaders condemn russia invasion ...,"[dark, day, europe, world, leader, condemn, russia, invasion, ukraine, dark, day, europe, world, leader, condemn, ru...",dark day europe world leader condemn russia invasion ukraine dark day europe world leader condemn russia invasion uk...,2022-02-24,16:37:42,2022-02-25
4332,diplomacy,Here are the Russian oligarchs targeted in Biden’s sanctions,https://www.cnbc.com/2022/02/26/here-are-the-russian-oligarchs-targeted-in-bidens-sanctions.html?&qsearchterm=diplomacy,"A former KGB leader, a diamond mine executive and a deputy prime minister — these are just some of the roles held by...","A former KGB leader, a diamond mine executive and a deputy prime minister — these are just some of the roles held by...",Politics,2022-02-26 10:13:16+07:00,2022-02-26,03:13 AM,0.0,...,Here are the Russian oligarchs targeted in Biden s sanctions Here are the Russian oligarchs targeted in Biden s sanc...,here are the russian oligarchs targeted in biden s sanctions here are the russian oligarchs targeted in biden s sanc...,en,"[russian, oligarchs, targeted, biden, sanctions, russian, oligarchs, targeted, biden, sanctions, former, kgb, leader...",russian oligarchs targeted biden sanctions russian oligarchs targeted biden sanctions former kgb leader diamond mine...,"[russian, oligarch, target, biden, sanction, russian, oligarchs, target, biden, sanction, former, kgb, leader, diamo...",russian oligarch target biden sanction russian oligarchs target biden sanction former kgb leader diamond mine execut...,2022-02-26,10:13:16,2022-02-28
4333,diplomacy,"Ukraine is ‘not ready to surrender or capitulate’ to Russia, foreign minister says",https://www.cnbc.com/2022/02/28/ukraine-not-ready-to-surrender-or-capitulate-ukraine-foreign-minister.html?&qsearcht...,"Ukraine has vowed it will not surrender to Russia, as talks are held between delegates from both countries following...","Ukraine has vowed it will not surrender to Russia, as talks are held between delegates from both countries following...",Europe Politics,2022-02-28 21:33:07+07:00,2022-02-28,02:33 PM,0.0,...,Ukraine is not ready to surrender or capitulate to Russia foreign minister says Ukraine is not ready to surrender or...,ukraine is not ready to surrender or capitulate to russia foreign minister says ukraine is not ready to surrender or...,en,"[ukraine, ready, surrender, capitulate, russia, foreign, minister, ukraine, ready, surrender, capitulate, russia, fo...",ukraine ready surrender capitulate russia foreign minister ukraine ready surrender capitulate russia foreign ministe...,"[ukraine, ready, surrender, capitulate, russia, foreign, minister, ukraine, ready, surrender, capitulate, russia, fo...",ukraine ready surrender capitulate russia foreign minister ukraine ready surrender capitulate russia foreign ministe...,2022-02-28,21:33:07,2022-03-01
4334,diplomacy,Huge Russian convoy approaches Kyiv as fears of all-out assault on the city grow,https://www.cnbc.com/2022/03/01/huge-convoy-of-russian-vehicles-approaching-kyiv.html?&qsearchterm=diplomacy,Russia appears to be advancing in its invasion of Ukraine with satellite imagery indicating that a huge convoy — som...,Russia appears to be advancing in its invasion of Ukraine with satellite imagery indicating that a huge convoy — som...,Europe Politics,2022-03-01 15:09:58+07:00,2022-03-01,08:09 AM,0.0,...,Huge Russian convoy approaches Kyiv as fears of all out assault on the city grow Huge Russian convoy approaches Kyiv...,huge russian convoy approaches kyiv as fears of all out assault on the city grow huge russian convoy approaches kyiv...,en,"[huge, russian, convoy, approaches, kyiv, fears, assault, city, grow, huge, russian, convoy, approaches, kyiv, fears...",huge russian convoy approaches kyiv fears assault city grow huge russian convoy approaches kyiv fears assault city g...,"[huge, russian, convoy, approach, kyiv, fear, assault, city, grow, huge, russian, convoy, approach, kyiv, fear, assa...",huge russian convoy approach kyiv fear assault city grow huge russian convoy approach kyiv fear assault city grow ru...,2022-03-01,15:09:58,2022-03-02
4335,diplomacy,"North Korea is developing a new long-range missile system, U.S. official says",https://www.cnbc.com/2022/03/10/north-korea-developing-new-long-range-missile-system-us-official-says.html?&qsearcht...,WASHINGTON — The Biden administration confirmed Thursday that North Korea recently conducted two tests of a relative...,WASHINGTON — The Biden administration confirmed Thursday that North Korea recently conducted two tests of a relative...,Politics,2022-03-11 04:01:23+07:00,2022-03-10,09:01 PM,0.0,...,North Korea is developing a new long range missile system U S official says North Korea is developing a new long ran...,north korea is developing a new long range missile system u s official says north korea is developing a new long ran...,en,"[north, korea, developing, new, long, range, missile, system, official, north, korea, developing, new, long, range, ...",north korea developing new long range missile system official north korea developing new long range missile system o...,"[north, korea, develop, new, long, range, missile, system, official, north, korea, develop, new, long, range, missil...",north korea develop new long range missile system official north korea develop new long range missile system officia...,2022-03-11,04:01:23,2022-03-11

In [23]:
daily_news = news.groupby('aligned_trading_date').agg(
    news_count=('title', 'count'),
    all_titles=('title', lambda x: ' | '.join(x)),
    all_text_lemmatized=('text_lemmatized', lambda x: ' | '.join(x))
).reset_index()

In [24]:
merged_data = pd.merge(
    bi_raw,
    daily_news,
    left_on='Tanggal_dt',                   
    right_on='aligned_trading_date',   
    how='left'
)

merged_data

,NO,Nilai,Kurs Jual,Kurs Beli,Tanggal_dt,tanggal,jam,Tanggal,aligned_trading_date,news_count,all_titles,all_text_lemmatized
0,1,1,17834.73,17657.27,2026-09-01,09/01/2026,12:00 AM,2026-09-01,2026-09-01,1.0,Oil prices rise as latest fighting resurrects Middle East supply disruption risks,oil price rise late fight resurrects middle east supply disruption risk oil price rise late fight resurrects middle ...
1,2,1,17791.51,17614.49,2026-08-31,08/31/2026,12:00 AM,2026-08-31,2026-08-31,7.0,"U.S. Treasury’s Bessent faces G20 diplomacy test amid tariffs, Iran war, bond turmoil | Russia preparing ‘massive st...",treasury bessent face g20 diplomacy test amid tariff iran war bond turmoil treasury bessent face g20 diplomacy test ...
2,3,1,17850.81,17673.19,2026-08-28,08/28/2026,12:00 AM,2026-08-28,2026-08-28,6.0,China’s super-rich fled Singapore. Now they want to come back | Trump’s Greenland fixation puts security at the hear...,china super rich flee singapore want come back china super rich flee singapore want come back year ago wealthy chine...
3,4,1,17805.58,17628.42,2026-08-27,08/27/2026,12:00 AM,2026-08-27,2026-08-27,1.0,Oil rises 2% as White House says no US-Iran talks happening,oil rise percent white house u iran talk happen oil rise percent white house u iran talk happen oil price rise thurs...
4,5,1,17791.51,17614.49,2026-08-26,08/26/2026,12:00 AM,2026-08-26,2026-08-26,4.0,The ‘debasement trade’ returns after Bessent bond maneuver. Crypto and gold are back in style | World Liberty Financ...,debasement trade return bessent bond maneuver crypto gold back style debasement trade return bessent bond maneuver c...
...,...,...,...,...,...,...,...,...,...,...,...,...
1197,1198,1,14310.20,14167.81,2021-09-07,09/07/2021,12:00 AM,2021-09-07,NaT,NaN,NaN,NaN
1198,1199,1,14332.31,14189.70,2021-09-06,09/06/2021,12:00 AM,2021-09-06,2021-09-06,1.0,"Inflation could repeat the 1960s, when the Fed lost control, Niall Ferguson says",inflation repeat 1960s fed lose control niall ferguson inflation repeat 1960s fed lose control niall ferguson inflat...
1199,1200,1,14352.41,14209.60,2021-09-03,09/03/2021,12:00 AM,2021-09-03,NaT,NaN,NaN,NaN
1200,1201,1,14355.42,14212.58,2021-09-02,09/02/2021,12:00 AM,2021-09-02,NaT,NaN,NaN,NaN
1201,1202,1,14377.53,14234.47,2021-09-01,09/01/2021,12:00 AM,2021-09-01,NaT,NaN,NaN,NaN

In [25]:
# --- CEK HASIL CUTOFF (pakai date_raw_dt yang sudah WIB) ---
news['jam'] = news['date_raw_dt'].dt.time
news['weekday'] = news['date_raw_dt'].dt.day_name()
news['lewat_cutoff'] = news['date_raw_dt'].dt.time > pd.Timestamp("15:15:00").time()

# Tampilkan berita yang persis di sekitar jam cutoff (14:50 - 15:30) untuk dicek manual
mask_sekitar_cutoff = news['jam'].apply(lambda t: (t.hour == 15 and t.minute <= 30) or (t.hour == 14 and t.minute >= 50))
cek_cutoff = news.loc[mask_sekitar_cutoff, ['title', 'date_raw_dt', 'jam', 'weekday', 'lewat_cutoff', 'aligned_trading_date']]
print(cek_cutoff.sort_values('date_raw_dt').to_string(index=False))

# Cek kasus weekend shifting (berita Jumat setelah cutoff -> harus jadi Senin)
mask_weekend_case = news['weekday'].isin(['Friday', 'Saturday', 'Sunday'])
cek_weekend = news.loc[mask_weekend_case, ['title', 'date_raw_dt', 'weekday', 'lewat_cutoff', 'aligned_trading_date']]
print(cek_weekend.sort_values('date_raw_dt').to_string(index=False))

                                                                                                         title         date_raw_dt      jam   weekday  lewat_cutoff aligned_trading_date
                                        Facebook whistleblower behind major leak is going to testify in Europe 2021-10-12 14:58:07 14:58:07   Tuesday         False           2021-10-12
                                                    What is Putin’s greatest worry right now? His own citizens 2021-10-14 15:17:54 15:17:54  Thursday          True           2021-10-15
                                               10-year Treasury yield dips as bond market volatility continues 2021-10-29 15:08:09 15:08:09    Friday         False           2021-11-01
               ‘Zero trust’ and mutual dislike: Why hopes to resolve U.S.-Russia tensions are low as talks ... 2022-01-10 15:13:44 15:13:44    Monday         False           2022-01-11
                                                      Oil edges higher on tight supply, limited omicron impact 2022-01-17 14:51:50 14:51:50    Monday         False           2022-01-17
                                 Treasury prices gain, yields fall in flight to safety on Russia-Ukraine fears 2022-02-11 15:00:36 15:00:36    Friday         False           2022-02-14
                                  Now that Russia has invaded Ukraine, the West has to try to stop Putin — ... 2022-02-24 15:05:39 15:05:39  Thursday         False           2022-02-25
                             Veteran investor Mark Mobius explains why bitcoin is rallying amid Ukraine crisis 2022-03-01 14:53:40 14:53:40   Tuesday         False           2022-03-01
                              Huge Russian convoy approaches Kyiv as fears of all-out assault on the city grow 2022-03-01 15:09:58 15:09:58   Tuesday         False           2022-03-02
                                        World’s largest shipping companies suspend bookings to and from Russia 2022-03-03 14:56:00 14:56:00  Thursday         False           2022-03-03
                                        Putin’s always wanted to weaken the West. He’s done the exact opposite 2022-03-09 15:27:15 15:27:15 Wednesday          True           2022-03-10
                                      If Putin uses chemical weapons in Ukraine it’s a ‘game changer’ for NATO 2022-03-14 15:30:25 15:30:25    Monday          True           2022-03-15
                             Putin’s invasion of Ukraine is seen as his biggest ever mistake — and it will ... 2022-03-24 15:25:04 15:25:04  Thursday          True           2022-03-25
     India pushes for demilitarization of border during Chinese foreign minister’s surprise visit to New Delhi 2022-03-25 15:25:01 15:25:01    Friday          True           2022-03-28
               The invasion of Ukraine has serious, unintended consequences for Russia. Here are just 5 of ... 2022-03-29 15:18:27 15:18:27   Tuesday          True           2022-03-30
                                      Germany warns of possible natural gas rationing amid dispute with Russia 2022-03-30 15:13:41 15:13:41 Wednesday         False           2022-03-31
                      Putin is preparing an eastern offensive in Ukraine. Here’s how this phase of the war ... 2022-04-07 15:20:25 15:20:25  Thursday          True           2022-04-08
                       Treasury yields jump after Fed’s Powell hints a 50-basis-point rate hike for next month 2022-04-21 15:03:03 15:03:03  Thursday         False           2022-04-22
                             Treasury yields slump to start the week as fears of a Covid breakout in China ... 2022-04-25 15:02:21 15:02:21    Monday         False           2022-04-26
                            Russia accused of ‘blackmail’ after halting gas supplies to two European countries 2022-04-27 15:01:04 15:01:04 Wednesday         False           2022-04-28
                                 China should heed ‘strong Western response’ to Russia’s war, says ex-diplomat 2022-05-13 15:25:28 15:25:28    Friday          True           2022-05-16
                               EU struggles to reach an agreement on Russian oil embargo as Hungary holds firm 2022-05-30 15:28:02 15:28:02    Monday          True           2022-05-31
                 The West’s unity over Ukraine could be starting to crack, just as Russia’s invasion gains ... 2022-06-16 15:15:19 15:15:19  Thursday          True           2022-06-17
                            Moscow and NATO could be about to clash over Russia’s European exclave Kaliningrad 2022-06-22 15:18:11 15:18:11 Wednesday          True           2022-06-23
                                Russian shelling hits chemical plant where civilians are trapped, says Ukraine 2022-06-25 15:30:00 15:30:00  Saturday          True           2022-06-27
                         ‘We are not scared’: Italy’s De Nora set for market debut in Europe’s first major ... 2022-06-28 15:28:18 15:28:18   Tuesday          True           2022-06-29
                                    U.S.-Chinatensionsare not helping Biden in inflation fight, economist says 2022-08-18 15:09:03 15:09:03  Thursday         False           2022-08-19
                                  U.S.-China tensions are not helping Biden in inflation fight, economist says 2022-08-18 15:09:03 15:09:03  Thursday         False           2022-08-19
                                    India’s PM Modi says he’s keen to boost ties with Russia, including energy 2022-09-08 15:18:39 15:18:39  Thursday          True           2022-09-09
                                         Airline tickets could become even more expensive, aviation execs warn 2022-09-22 14:59:52 14:59:52  Thursday         False           2022-09-22
                                    Ukraine celebrates recapturing key town, Putin ally raises nuclear jitters 2022-10-02 14:50:23 14:50:23    Sunday         False           2022-10-03
                    U.S. delivers angry rebuke of massive OPEC+ production cut — and it could backfire for ... 2022-10-06 15:27:54 15:27:54  Thursday          True           2022-10-07
                                         Dollar plunges as U.S. inflation data spurs exodus from crowded trade 2022-11-10 15:08:33 15:08:33  Thursday         False           2022-11-11
                   Putin’s military command reshuffle reveals a power struggle at the heart of the Ukraine war 2023-01-13 15:29:19 15:29:19    Friday          True           2023-01-16
                      Blackouts, currency dives and corruption: Pakistan’s economy is on the brink of collapse 2023-02-03 15:17:44 15:17:44    Friday          True           2023-02-06
                       ‘Our phones are ringing off the hook’: Amid a global downturn, the finance world is ... 2023-03-09 15:21:41 15:21:41  Thursday          True           2023-03-10
                       The U.S. imposed semiconductor export controls on China. Now a key EU nation is set ... 2023-03-09 15:29:53 15:29:53  Thursday          True           2023-03-10
                            U.S. and China trade barbs at top security summit as Taiwan Strait tensions simmer 2023-06-05 15:09:05 15:09:05    Monday         False           2023-06-06
                                               Singapore state investor Temasek posts worst returns since 2016 2023-07-11 15:00:32 15:00:32   Tuesday         False           2023-07-12
                         Emerging economies group BRICS invites 6 new members, including Saudi Arabia and Iran 2023-08-24 14:59:42 14:59:42  Thursday         False           2023-08-24
                    EV makers such as Tesla could fall under Europe’s subsidy probe into China, EU’s trade ... 2023-09-28 15:27:25 15:27:25  Thursday          True           2023-09-29
        ‘Fraught with uncertainty’: IEA says oil markets to remain on tenterhooks as Israel-Hamas war persists 2023-10-12 15:00:39 15:00:39  Thursday         False           2023-10-13
                               Russia can gain from Middle East turmoil — but it could backfire if the war ... 2023-10-13 14:56:43 14:56:43    Friday         False           2023-10-13
                                         Putin meets ‘dear friend’ Xi in Beijing. Here are the top 3 takeaways 2023-10-18 15:20:04 15:20:04 Wednesday          True           2023-10-19
                            Renewed Gaza fighting stretches into second day after Israel-Hamas truce collapses 2023-12-02 14:57:12 14:57:12  Saturday         False           2023-12-04
              Houthi attacks rocking Red Sea trade routes likely won’t end anytime soon. Here’s what could ... 2023-12-21 15:05:34 15:05:34  Thursday         False           2023-12-22
                       Divide between political elites and the working class is a major risk, Allianz CEO says 2024-01-16 15:23:02 15:23:02   Tuesday          True           2024-01-17
                        Divide between political elites and the working class is a majorrisk, Allianz CEO says 2024-01-16 15:23:02 15:23:02   Tuesday          True           2024-01-17
               Markets getting ahead of themselves on rate cuts andriskbeing ‘self-defeating,’ ECB member says 2024-01-17 14:58:13 14:58:13 Wednesday         False           2024-01-17
                      India set to clock up to 8% GDP growth as it boosts manufacturing capacity, minister ... 2024-02-02 15:02:02 15:02:02    Friday         False           2024-02-05
                            Putin vows to punish Ukraine for attacks as Russians vote in presidential election 2024-03-16 14:56:40 14:56:40  Saturday         False           2024-03-18
                               U.S. accuses Russia of using chemical weapons in Ukraine, in breach ofglobalban 2024-05-02 14:50:40 14:50:40  Thursday         False           2024-05-02
              ‘Biggest barrier’ to Saudi-Israeli normalization is the two-state solution, says ex-CIA director 2024-05-16 15:10:39 15:10:39  Thursday         False           2024-05-17
                               Europe is reckoning with a ‘much more unpredictable’ U.S., former EU chief says 2024-06-11 15:15:47 15:15:47   Tuesday          True           2024-06-12
                                               Inside Europe’s tech hubs: France’s AI push puts it on the rise 2024-06-27 15:28:47 15:28:47  Thursday          True           2024-06-28
                    NATO condemns China as a ‘decisive enabler’ of Russia’s war in Ukraine in most serious ... 2024-07-11 15:15:52 15:15:52  Thursday          True           2024-07-12
                                           Apple must pay 13 billion euros in back taxes, EU’s top court rules 2024-09-10 14:56:33 14:56:33   Tuesday         False           2024-09-10
         Netanyahu says killing of Hezbollah leader Hassan Nasrallah in Israeli airstrike ‘will not be enough’ 2024-09-28 15:25:06 15:25:06  Saturday          True           2024-09-30
                Oil markets not pricing in an ‘all-out war’ after Israel kills Hezbollah leader, but risks ... 2024-09-30 15:08:25 15:08:25    Monday         False           2024-10-01
                                Britain’s defense sector vies for stretched government funding on path to 2.5% 2024-10-04 15:18:50 15:18:50    Friday          True           2024-10-07
                             North Korea blows up parts of inter-Korean road on its side of border, Seoul says 2024-10-15 14:51:53 14:51:53   Tuesday         False           2024-10-15
                                                Israel pounds Beirut and Gaza after rockets hit Israel’s north 2024-10-20 15:16:57 15:16:57    Sunday          True           2024-10-21
                   China tightens export controls for tech and goods with military use, ahead of Xi’s trip ... 2024-10-21 15:30:58 15:30:58    Monday          True           2024-10-22
                                     Russia pushes ‘new world order’ agenda as it hosts beefed-up BRICS summit 2024-10-22 14:50:04 14:50:04   Tuesday         False           2024-10-22
South and North Korea troops potentially entering Ukraine war unlikely to stoke regionalconflict, analysts ... 2024-10-25 14:58:51 14:58:51    Friday         False           2024-10-25
                                             Oil prices fall slightly as investors take stock of Trump victory 2024-11-06 15:05:26 15:05:26 Wednesday         False           2024-11-07
                      Adani Green soars 19% as group stocks recover sharply amid ongoing U.S. legal challenges 2024-11-29 14:58:09 14:58:09    Friday         False           2024-11-29
                                           Contentious budget plans are wreaking political havoc across Europe 2024-12-04 15:25:14 15:25:14 Wednesday          True           2024-12-05
                    China’s economy is waiting for more stimulus. Here’s how the country plans to boost growth 2025-01-16 15:01:18 15:01:18  Thursday         False           2025-01-17
                                                    Auto stocks fall as Trump tariffs spark trade war concerns 2025-02-03 15:21:07 15:21:07    Monday          True           2025-02-04
                                     Talks to end the war with Russia are set to begin — but Ukraine could ... 2025-02-13 15:13:35 15:13:35  Thursday         False           2025-02-14
                  Hong Kong government earmarks $128 million for new AI research institute and aims to cut ... 2025-02-26 15:23:48 15:23:48 Wednesday          True           2025-02-27
                                     Trump signals U.S. and U.K. could reach ‘real trade deal’ without tariffs 2025-02-28 15:02:16 15:02:16    Friday         False           2025-03-03
                    Russia’s Putin says it would be a ‘profound mistake’ to dismiss Trump’s push for Greenland 2025-03-28 15:22:24 15:22:24    Friday          True           2025-03-31
           The oil-rich Gulf states are better-positioned to weather the tariff storm — but crashing crude ... 2025-04-09 15:30:46 15:30:46 Wednesday          True           2025-04-10
                                          Iran says ‘extremely cautious’ on success of nuclear talks with U.S. 2025-04-27 14:56:12 14:56:12    Sunday         False           2025-04-28
                         Dutch PM steps down after far-right party leaves coalition over immigration proposals 2025-06-03 14:57:09 14:57:09   Tuesday         False           2025-06-03
                                   Boeing Dreamliner crash, military escalations darken mood at Paris Air Show 2025-06-15 15:00:01 15:00:01    Sunday         False           2025-06-16
                                             Iran and Israel announce more strikes asconflictenters fourth day 2025-06-16 15:22:02 15:22:02    Monday          True           2025-06-17
                           The Iran-Israel conflict isn’t denting Chinese business optimism in the Middle East 2025-06-23 15:24:36 15:24:36    Monday          True           2025-06-24
                             The Iran-Israelconflictisn’t denting Chinese business optimism in the Middle East 2025-06-23 15:24:36 15:24:36    Monday          True           2025-06-24
                         Oil tumbles for a second day, loses 6% as Iran-Israel ceasefire eases supply concerns 2025-06-24 15:09:51 15:09:51   Tuesday         False           2025-06-25
                                             Thai protesters call for Prime Minister Paetongtarn’s resignation 2025-06-28 15:05:25 15:05:25  Saturday         False           2025-06-30
                         European powers threaten ‘snapback sanctions’ if Iran doesn’t return to nuclear talks 2025-08-13 15:04:53 15:04:53 Wednesday         False           2025-08-14
                                                    Five things at stake in Trump and Putin’s high-level talks 2025-08-15 15:19:48 15:19:48    Friday          True           2025-08-18
                          Trump advisor Peter Navarro slams India’s ‘opportunistic’ purchases of Russian crude 2025-08-18 14:53:59 14:53:59    Monday         False           2025-08-18
                                                                       Oil rises after Israeli attack in Qatar 2025-09-09 15:14:46 15:14:46   Tuesday         False           2025-09-10
                                          China says Nvidia violated anti-monopoly law after preliminary probe 2025-09-15 15:25:45 15:25:45    Monday          True           2025-09-16
                                      The pomp and pageantry ends as Trump’s state visit gets down to business 2025-09-18 15:12:04 15:12:04  Thursday         False           2025-09-19
                  CNBC’s The China Connection newsletter: China’s K-visa plans spark worries of a talent flood 2025-10-01 15:26:07 15:26:07 Wednesday          True           2025-10-02
                      Putin warns of ‘new stage of escalation’ if U.S. supplies long-range missiles to Ukraine 2025-10-03 14:51:24 14:51:24    Friday         False           2025-10-03
                                       Trump puts Russia on notice over Ukraine as two leaders prepare to meet 2025-10-17 15:18:39 15:18:39    Friday          True           2025-10-20
                                        Trump oversees truce signing and trade deal flurry on first Asian stop 2025-10-26 14:59:03 14:59:03    Sunday         False           2025-10-27
                   India now incurs higher U.S. tariffs than China. What does it say about Trump’s foreign ... 2025-11-03 15:00:17 15:00:17    Monday         False           2025-11-04
                       Binance CEO dismisses claims the firm boosted a Trump crypto venture ahead of CZ pardon 2025-11-04 15:27:43 15:27:43   Tuesday          True           2025-11-05
                   India is set to host Russia’s Putin, deepening trade ties, unfazed by punitive U.S. tariffs 2025-12-03 15:29:22 15:29:22 Wednesday          True           2025-12-04
                              The UK wants to unlock a ‘golden age of nuclear’ but faces key challenges in ... 2025-12-06 14:55:27 14:55:27  Saturday         False           2025-12-08
                             What investors are watching after Venezuela: Five signals that matter for markets 2026-01-05 15:10:58 15:10:58    Monday         False           2026-01-06
           Greenland’s freshwater reserves seen as ‘frozen capital’ as water becomes a national security issue 2026-01-20 15:11:13 15:11:13   Tuesday         False           2026-01-21
                CNBC’s The China Connection newsletter: China’s new global playbook —from exporter to investor 2026-01-21 15:28:51 15:28:51 Wednesday          True           2026-01-22
                CNBC’s Inside India newsletter: India, EU eye ‘mother of all deals’ amid U.S.tensions. But ... 2026-01-22 15:27:55 15:27:55  Thursday          True           2026-01-23
               CNBC’s Inside India newsletter: India, EU eye ‘mother of all deals’ amid U.S. tensions. But ... 2026-01-22 15:27:55 15:27:55  Thursday          True           2026-01-23
                       Puma shares surge after Anta Sports buys stake for $1.8 billion amid turnaround efforts 2026-01-27 15:04:42 15:04:42   Tuesday         False           2026-01-28
                           ‘Devil in the details’: India-U.S. deal raises hopes for a reset — but the fine ... 2026-02-03 14:53:34 14:53:34   Tuesday         False           2026-02-03
                                   These four charts show how reliant Europe is on U.S. digital infrastructure 2026-02-13 15:30:43 15:30:43    Friday          True           2026-02-16
                             Why Chile is the latest LATAM country to be caught in a U.S.-China power struggle 2026-02-25 14:50:27 14:50:27 Wednesday         False           2026-02-25
                        Oil soars amid Strait of Hormuz shipping fears as Iran war drives prices to nearly ... 2026-03-02 15:06:44 15:06:44    Monday         False           2026-03-03

In [26]:
tanggal_dicek = cek_cutoff['aligned_trading_date'].unique()

for tgl in tanggal_dicek:
    subset = merged_data[merged_data['aligned_trading_date'] == tgl]
    print(f"\n=== Trading date: {tgl.date()} ===")
    print(f"Jumlah berita ter-merge: {subset['news_count'].values}")
    # tampilkan judul2 berita yg masuk ke tanggal ini dari df news asli
    judul_masuk = news[news['aligned_trading_date'] == tgl][['title', 'published_raw']]
    print(judul_masuk.sort_values('published_raw').to_string(index=False))

=== Trading date: 2026-07-07 ===
Jumlah berita ter-merge: [3.]
                                                                             title             published_raw
Trump’s calls, Ukraine’s strikes and Russia’s barrage on Kyiv put markets on alert 2026-07-06 15:27:36+07:00
                     Oil prices gain as focus shifts to supply recovery and demand 2026-07-07 08:10:02+07:00
                            Dollar higher after data as yen holds near 40-year low 2026-07-07 08:16:23+07:00

=== Trading date: 2026-06-08 ===
Jumlah berita ter-merge: [10.]
                                                                                 title             published_raw
10-year Treasury yield surges above 4.53% as hot jobs report dents hopes for rate cuts 2026-06-05 15:05:07+07:00
                    Bitcoin cracks $60,000, sinking to lowest level since October 2024 2026-06-05 18:41:45+07:00
    Hot jobs report puts Fed cuts further out of reach as Chair Warsh faces policy ... 2026-06-06 00:44:14+07:00
                 U.S. eyes Iranian assets for Gulf allies’ reconstruction, source says 2026-06-06 18:09:52+07:00
    100 days of the Iran war: Howglobalmarkets and the economy have been affected, ... 2026-06-07 12:00:01+07:00
  100 days of the Iran war: How global markets and the economy have been affected, ... 2026-06-07 12:00:01+07:00
          Top Wall Street analysts recommend these 3 dividend stocks for solid returns 2026-06-07 19:21:24+07:00
            Inflation inside the electronics you buy may soon become a bit more sticky 2026-06-07 20:59:37+07:00
    China’s Xi to visit North Korea for first time in seven years as Beijing tests ... 2026-06-08 08:38:47+07:00
                          SoftBank drops 6% as tech stock sell-off accelerates in Asia 2026-06-08 10:24:21+07:00

=== Trading date: 2024-01-17 ===
Jumlah berita ter-merge: [12.]
                                                                                          title             published_raw
         Divide between political elites and the working class is a majorrisk, Allianz CEO says 2024-01-16 15:23:02+07:00
        Divide between political elites and the working class is a major risk, Allianz CEO says 2024-01-16 15:23:02+07:00
         ‘We have a huge fiscal problem’: Banking group IIF sounds the alarm on recordglobal... 2024-01-16 18:25:02+07:00
      Morgan Stanley revenue tops estimates, but CEO warns ofgeopolitical, economic risks ahead 2024-01-16 19:35:02+07:00
                             China’s Taiwan approach ‘has been counterproductive,’ Blinken says 2024-01-17 03:01:34+07:00
    Red Seariskto oil ‘very real,’ prices could change rapidly if supply disrupted, Chevron ... 2024-01-17 03:25:55+07:00
  Red Sea risk to oil ‘very real,’ prices could change rapidly if supply disrupted, Chevron ... 2024-01-17 03:25:55+07:00
                                                           CNBC Daily Open: Fed’s reality check 2024-01-17 06:56:24+07:00
                          Oil near flat as extreme cold’s hit to U.S. output offsets China data 2024-01-17 09:35:39+07:00
               Iran warns the U.S. not to ‘tie their destiny’ to the fate of Israel’s Netanyahu 2024-01-17 11:41:17+07:00
                                                      CNBC Daily Open: The Fed’s rude awakening 2024-01-17 14:30:01+07:00
Markets getting ahead of themselves on rate cuts andriskbeing ‘self-defeating,’ ECB member says 2024-01-17 14:58:13+07:00

=== Trading date: 2026-02-25 ===
Jumlah berita ter-merge: [5.]
                                                                                      title             published_raw
South Korea and Japan stocks hit fresh highs amid regional gains after Wall Street’s AI ... 2026-02-25 06:47:02+07:00
                The global M&A boom is rolling into 2026 as AI sparks deal frenzy — but ... 2026-02-25 08:33:55+07:00
            Trump says Iran wants a deal more than the U.S. as American forces build up ... 2026-02-25 08:34:11+07:00
                                        5 takeaways from Trump’s State of the Union address 2026-02-25 13:39:53+07:00
          Why Chile is the latest LATAM country to be caught in a U.S.-China power struggle 2026-02-25 14:50:27+07:00

=== Trading date: 2026-04-17 ===
Jumlah berita ter-merge: [10.]
                                                                                     title             published_raw
EasyJet’s stock drops 5% as the Middle East conflict, fuel costs weigh on bookings outlook 2026-04-16 15:02:54+07:00
 EasyJet’s stock drops 5% as the Middle Eastconflict, fuel costs weigh on bookings outlook 2026-04-16 15:02:54+07:00
    Kering looks to double profits as it unveils ambitious turnaround plan to revive Gucci 2026-04-16 15:25:04+07:00
            PepsiCo earnings beat estimates as Doritos, Lay’s price cuts win back shoppers 2026-04-16 17:02:59+07:00
     ‘Guns vs. butter’: IMF flags tough trade-offs as governments ramp up defense spending 2026-04-16 18:03:35+07:00
         New York Fed President Williams worries war will slow growth, aggravate inflation 2026-04-16 19:35:22+07:00
     Retail traders pile into Allbirds after odd AI pivot. History shows it won’t end well 2026-04-16 22:47:09+07:00
U.S. oil price plunges below $84 as Iran declares Strait of Hormuz open, easing supply ... 2026-04-17 07:40:09+07:00
         U.S. seeks bigger energy foothold in India. Why it could be a problem for New ... 2026-04-17 14:08:22+07:00
  Nvidia rival tells CNBC it’s seeking at least $100 million in funding as European AI ... 2026-04-17 14:10:01+07:00

=== Trading date: 2025-10-02 ===
Jumlah berita ter-merge: [4.]
                                                                                       title             published_raw
CNBC’s The China Connection newsletter: China’s K-visa plans spark worries of a talent flood 2025-10-01 15:26:07+07:00
                                   What is the drone wall that Europe wants to deter Russia? 2025-10-01 16:12:00+07:00
                                  How a U.S. government shutdown could impact global markets 2025-10-01 20:19:39+07:00
Trump Jr. dismisses crypto conflicts of interest, says dad’s not checking blockchain ledgers 2025-10-02 13:39:36+07:00

=== Trading date: 2025-06-24 ===
Jumlah berita ter-merge: [16.]
                                                                                      title             published_raw
        The Iran-Israel conflict isn’t denting Chinese business optimism in the Middle East 2025-06-23 15:24:36+07:00
          The Iran-Israelconflictisn’t denting Chinese business optimism in the Middle East 2025-06-23 15:24:36+07:00
                                Dollar surge could be short-lived after U.S. strike on Iran 2025-06-23 15:51:19+07:00
                                                        Dollar falls on dovish Fed comments 2025-06-23 16:50:10+07:00
China’s support for Tehran grows more restrained as U.S. enters war between Israel and Iran 2025-06-23 17:41:33+07:00
   Shipping groups avoid the Strait of Hormuz to reduce exposure after U.S. strikes on Iran 2025-06-23 18:33:42+07:00
    Tankers showing caution around Strait of Hormuz after U.S. attack on Iran nuclear sites 2025-06-23 19:46:15+07:00
                 Where stock market’s safety trade has moved now that Apple is no longer it 2025-06-23 22:24:05+07:00
   U.S. intel found Iran did not move nuclear material from Fordo ahead of attack, Sen. ... 2025-06-23 23:16:06+07:00
     Airlines divert, cancel more Middle East flights after Iran attacks U.S. military base 2025-06-24 00:52:57+07:00
          RBN Energy executive explains why Iran isn’t likely to close the Strait of Hormuz 2025-06-24 06:24:15+07:00
                                 CNBC Daily Open: The strange times of missiles-led ‘peace’ 2025-06-24 08:18:53+07:00
                                                 Dollar drops after cease fire announcement 2025-06-24 11:18:31+07:00
                                Virgin Australia shares soar 8.3% in $439 million IPO debut 2025-06-24 11:20:59+07:00
                             Conflictor ceasefire, most markets remain unfazed — here’s why 2025-06-24 13:04:10+07:00
                           CNBC Daily Open: A confusing ceasefire forged by missile attacks 2025-06-24 13:30:02+07:00

=== Trading date: 2023-10-13 ===
Jumlah berita ter-merge: [5.]
                                                                                                  title             published_raw
 ‘Fraught with uncertainty’: IEA says oil markets to remain on tenterhooks as Israel-Hamas war persists 2023-10-12 15:00:39+07:00
Bloodshed, destruction and a far-off peace? There are several possible outcomes of the Israel-Hamas war 2023-10-12 20:06:59+07:00
           Europe is investigating Elon Musk’s X about Israel-Hamas misinformation, violence on the app 2023-10-13 06:47:17+07:00
                                                                   Dollar up after inflation data boost 2023-10-13 09:39:23+07:00
                        Russia can gain from Middle East turmoil — but it could backfire if the war ... 2023-10-13 14:56:43+07:00

=== Trading date: 2024-12-05 ===
Jumlah berita ter-merge: [3.]
                                                                                             title             published_raw
                               Contentious budget plans are wreaking political havoc across Europe 2024-12-04 15:25:14+07:00
              Far from a bazooka, China’s stimulus measures are just trickling through the economy 2024-12-05 06:05:41+07:00
‘Last minute spending spree’ by Biden, including Rivian loan, to get DOGE scrutiny, says Vivek ... 2024-12-05 06:30:54+07:00

=== Trading date: 2024-11-29 ===
Jumlah berita ter-merge: [5.]
                                                                                          title             published_raw
Undersea cable cuts in the Baltic Sea are stokinggeopoliticaltensions — here’s what’s going ... 2024-11-28 20:30:51+07:00
 Undersea cable cuts in the Baltic Sea are stokinggeopoliticaltensions— here’s what’s going ... 2024-11-28 20:30:51+07:00
                 Mexico warns Trump tariffs would kill 400,000 U.S. jobs, threatens retaliation 2024-11-28 23:11:03+07:00
                       Lebanon had ‘no say in the decision to go to war,’ foreign minister says 2024-11-29 00:29:46+07:00
       Adani Green soars 19% as group stocks recover sharply amid ongoing U.S. legal challenges 2024-11-29 14:58:09+07:00

=== Trading date: 2022-08-19 ===
Jumlah berita ter-merge: [3.]
                                                                                 title             published_raw
          U.S.-China tensions are not helping Biden in inflation fight, economist says 2022-08-18 15:09:03+07:00
            U.S.-Chinatensionsare not helping Biden in inflation fight, economist says 2022-08-18 15:09:03+07:00
‘You’ve got to eat’: Energy bills are squeezing businesses and people as UK costs soar 2022-08-19 12:24:27+07:00

=== Trading date: 2026-03-17 ===
Jumlah berita ter-merge: [3.]
                                                                                  title             published_raw
 Oil’s war-driven volatility pulls in record retail money, fueling ‘meme-style’ trading 2026-03-16 15:02:05+07:00
Treasury yields drop as investors track lower oil prices and look ahead to Fed rate ... 2026-03-16 18:01:32+07:00
  Strait of Hormuz standoff puts supply of America’s generic drug prescriptions at risk 2026-03-16 18:20:34+07:00

=== Trading date: 2026-07-01 ===
Jumlah berita ter-merge: [5.]
                                                                                   title             published_raw
Inflation likely to stay ‘significantly above target,’ top European central banker warns 2026-06-30 15:00:30+07:00
        AeroVironment skyrockets 19% as dronemaker capitalizes on defense spending surge 2026-06-30 20:24:04+07:00
                    Oil prices rise as breakdown in Iran-US talks raises supply concerns 2026-07-01 11:23:24+07:00
  North Sea oil and renewables: The UK’s next PM faces a defining energy policy decision 2026-07-01 13:28:00+07:00
                Europe’s defense boom faces a new test: Can it actually deliver weapons? 2026-07-01 14:18:52+07:00

=== Trading date: 2026-06-24 ===
Jumlah berita ter-merge: [4.]
                                                                                         title             published_raw
     U.S. issues sweeping Iran oil sanctions waivers, unlocking billions in revenue for Tehran 2026-06-23 15:10:24+07:00
                   Factory job cuts in June neared financial crisis and Covid levels, S&P says 2026-06-23 21:32:23+07:00
                   Ukraine is raising the cost of war for Russia — and testing Putin’s resolve 2026-06-24 12:00:01+07:00
Morgan Stanley doubles China humanoid robot shipment forecast as commercialization accelerates 2026-06-24 13:39:10+07:00

=== Trading date: 2026-01-23 ===
Jumlah berita ter-merge: [5.]
                                                                                          title             published_raw
CNBC’s Inside India newsletter: India, EU eye ‘mother of all deals’ amid U.S. tensions. But ... 2026-01-22 15:27:55+07:00
 CNBC’s Inside India newsletter: India, EU eye ‘mother of all deals’ amid U.S.tensions. But ... 2026-01-22 15:27:55+07:00
       Tougher stance on Trump is ‘very good for business’, says JP Morgan’s Europe boss as ... 2026-01-22 17:08:21+07:00
                Trump signed his Gaza ‘Board of Peace’ into being. Here’s who’s on it — and ... 2026-01-22 19:45:04+07:00
                           Yen choppy after BOJ holds rates, dollar faces worst week since June 2026-01-23 14:37:20+07:00

=== Trading date: 2025-08-18 ===
Jumlah berita ter-merge: []
                                                                                     title             published_raw
                                Five things at stake in Trump and Putin’s high-level talks 2025-08-15 15:19:48+07:00
       Trump says no summit deal with Putin over Ukraine war, talks were ‘very productive’ 2025-08-16 11:21:30+07:00
White House envoy claims Russia agreed to ‘Article 5-like’ security guarantees for Ukraine 2025-08-17 21:38:46+07:00
       CNBC Daily Open: Trump’s ‘peace’ for Ukraine doesn’t seem like what Zelenskyy wants 2025-08-18 13:30:01+07:00
      Trump advisor Peter Navarro slams India’s ‘opportunistic’ purchases of Russian crude 2025-08-18 14:53:59+07:00

=== Trading date: 2025-12-04 ===
Jumlah berita ter-merge: [1.]
                                                                                      title             published_raw
India is set to host Russia’s Putin, deepening trade ties, unfazed by punitive U.S. tariffs 2025-12-03 15:29:22+07:00

=== Trading date: 2026-01-28 ===
Jumlah berita ter-merge: [6.]
                                                                                  title             published_raw
Puma shares surge after Anta Sports buys stake for $1.8 billion amid turnaround efforts 2026-01-27 15:04:42+07:00
 ‘A day of celebration’: What the blockbuster EU-India trade deal means for auto giants 2026-01-27 18:24:30+07:00
    Fed is likely to lower rates only two more times, even under Trump’s next chair ... 2026-01-27 20:00:19+07:00
  Uncle Sam’s rare earth stake, Nike layoffs, five years of meme stocks and more in ... 2026-01-27 20:21:29+07:00
           Trump administration sued over 2 deaths in boat strike off Venezuela’s coast 2026-01-27 23:48:58+07:00
                     Dollar pinned near four-year low after Trump comments fuel selling 2026-01-28 12:21:32+07:00

=== Trading date: 2026-01-06 ===
Jumlah berita ter-merge: [7.]
                                                                                                   title             published_raw
                       What investors are watching after Venezuela: Five signals that matter for markets 2026-01-05 15:10:58+07:00
                     Global defense stocks soar as U.S. strike on Venezuela heralds new ‘hard power’ era 2026-01-05 16:18:26+07:00
U.S. stocks show little reaction to Trump’s extraordinary Venezuela action. Why investors see a bull ... 2026-01-05 20:26:44+07:00
                           Asian defense stocks extend rally as Venezuela tensions linger, markets mixed 2026-01-06 07:29:09+07:00
                             Asian defense stocks extend rally as Venezuelatensionslinger, markets mixed 2026-01-06 07:29:09+07:00
                                               CNBC Daily Open: Another year ofgeopoliticaluncertainties 2026-01-06 08:25:01+07:00
                                             CNBC Daily Open: Another year of geopolitical uncertainties 2026-01-06 08:25:01+07:00

=== Trading date: 2025-12-08 ===
Jumlah berita ter-merge: [8.]
                                                                                             title             published_raw
                              Putin’s latest warning to Ukraine shows how unlikely a peace deal is 2025-12-05 19:07:29+07:00
                      Oil prices hold steady due to stalled Ukraine peace talks and supply outlook 2025-12-05 22:09:25+07:00
                  The UK wants to unlock a ‘golden age of nuclear’ but faces key challenges in ... 2025-12-06 14:55:27+07:00
                           Senior US diplomat calls EU policies bad for trans-Atlantic partnership 2025-12-07 05:56:12+07:00
                                         Chinese jets point radar at Japanese aircraft, Japan says 2025-12-08 07:24:13+07:00
China’s trade surplus tops $1 trillion despite Trump’s attempt to contain it. Here’s what that ... 2025-12-08 10:23:03+07:00
                                      European markets fall slightly as markets await Fed decision 2025-12-08 13:43:38+07:00
                          Ray Dalio says Middle East is becoming a ‘Silicon Valley of capitalists’ 2025-12-08 14:49:51+07:00

=== Trading date: 2022-11-11 ===
Jumlah berita ter-merge: [5.]
                                                                                           title             published_raw
                           Dollar plunges as U.S. inflation data spurs exodus from crowded trade 2022-11-10 15:08:33+07:00
                     Putin supporters left reeling by yet another Russian ‘surrender’ in Ukraine 2022-11-10 18:39:55+07:00
Biden expected to bring up Chinese economic practices, Taiwan and Russia’s war in Ukraine in ... 2022-11-10 23:00:20+07:00
                      The global shipping industry is facing a new problem — too many containers 2022-11-11 11:17:04+07:00
           Iran’s drones are unlikely to help Russia win in Ukraine — and could backfire for ... 2022-11-11 13:34:01+07:00

=== Trading date: 2022-03-10 ===
Jumlah berita ter-merge: [5.]
                                                                                                title             published_raw
                               Putin’s always wanted to weaken the West. He’s done the exact opposite 2022-03-09 15:27:15+07:00
                  U.S., UK resist calls for no-fly zone over Ukraine’s pleas: ’Our goal is to end ... 2022-03-10 02:03:48+07:00
Emerging markets ETFs are in ‘uncharted waters’ with Russian stock trading on pause, Morningstar says 2022-03-10 04:48:34+07:00
               S&P 500 falls on Thursday as stocks resume their downward move from Russia-Ukraine war 2022-03-10 06:05:19+07:00
                                            Oil settles down again; Russia to fulfil supply contracts 2022-03-10 13:54:33+07:00

=== Trading date: 2024-10-07 ===
Jumlah berita ter-merge: [8.]
                                                                                         title             published_raw
                Britain’s defense sector vies for stretched government funding on path to 2.5% 2024-10-04 15:18:50+07:00

# Ekstraksi Fitur NLP

In [27]:
from __future__ import annotations

import re
from dataclasses import dataclass, field

import numpy as np
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import pysentiment2 as ps
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

# 1. Sentimen berbasis Lexicon

In [28]:
# 1. VADER (general-purpose)
_vader = SentimentIntensityAnalyzer()
def compute_vader_sentiment(df: pd.DataFrame, text_col: str = "text_lemmatized") -> pd.DataFrame:

    scores = df[text_col].fillna("").apply(_vader.polarity_scores).apply(pd.Series)
    scores = scores.rename(columns={
        "neg": "vader_neg", "neu": "vader_neu",
        "pos": "vader_pos", "compound": "vader_compound",
    })
    return pd.concat([df.reset_index(drop=True), scores.reset_index(drop=True)], axis=1)


# 2. Loughran-McDonald (finance-specific)
_lm = ps.LM()  # dictionary bundled offline (LM.csv), tidak perlu koneksi internet
def compute_lm_sentiment(df: pd.DataFrame, text_col: str = "text_lemmatized") -> pd.DataFrame:
    def _score(text: str) -> pd.Series:
        tokens = _lm.tokenize(text if isinstance(text, str) else "")
        s = _lm.get_score(tokens)
        return pd.Series({
            "lm_positive": s["Positive"],
            "lm_negative": s["Negative"],
            "lm_polarity": s["Polarity"],
            "lm_subjectivity": s["Subjectivity"],
        })

    scores = df[text_col].apply(_score)
    return pd.concat([df.reset_index(drop=True), scores.reset_index(drop=True)], axis=1)


# 3. Indeks risiko geopolitik berbasis keyword density 
# Daftar sama seperti filter relevansi
DEFAULT_GPR_KEYWORDS = [
    "geopolitics", "geopolitical risk", "geopolitical tensions",
    "geopolitical fragmentation", "armed conflict", "global conflict",
    "international conflict", "military tensions", "national security",
    "sanctions", "trade war", "tariffs", "embargo", "export controls",
    "protectionism", "supply chain disruption", "diplomacy",
    "foreign policy", "nato", "brics", "opec", "g7",
]

def compute_gpr_density(
    df: pd.DataFrame,
    text_col: str = "lower_text",
    keywords: list[str] | None = None,
) -> pd.DataFrame:

    kw = keywords or DEFAULT_GPR_KEYWORDS
    pattern = re.compile("|".join(re.escape(k) for k in kw))

    def _count(text: str) -> int:
        if not isinstance(text, str) or not text:
            return 0
        return len(pattern.findall(text))

    hits = df[text_col].apply(_count)
    word_count = df[text_col].fillna("").str.split().apply(len).replace(0, 1)

    out = df.copy()
    out["gpr_hits"] = hits
    out["gpr_density"] = hits / word_count
    return out

# 4. Vectorization klasik: TF-IDF + SVD (LSA) untuk reduksi dimensi
@dataclass
class TfidfSvdExtractor:
    max_features: int = 5000
    n_components: int = 75
    ngram_range: tuple[int, int] = (1, 2)
    min_df: int = 5
    random_state: int = 42

    _vectorizer: TfidfVectorizer = field(init=False, default=None, repr=False)
    _svd: TruncatedSVD = field(init=False, default=None, repr=False)
    _is_fitted: bool = field(init=False, default=False, repr=False)

    def fit(self, texts: pd.Series) -> "TfidfSvdExtractor":
        self._vectorizer = TfidfVectorizer(
            max_features=self.max_features,
            ngram_range=self.ngram_range,
            min_df=self.min_df,
            sublinear_tf=True,
        )
        tfidf_matrix = self._vectorizer.fit_transform(texts.fillna(""))

        # n_components dibatasi supaya tidak melebihi jumlah fitur/dokumen train
        n_comp = min(self.n_components, tfidf_matrix.shape[1] - 1, tfidf_matrix.shape[0] - 1)
        self._svd = TruncatedSVD(n_components=max(n_comp, 2), random_state=self.random_state)
        self._svd.fit(tfidf_matrix)
        self._is_fitted = True
        return self

    def transform(self, texts: pd.Series) -> pd.DataFrame:
        if not self._is_fitted:
            raise RuntimeError("Panggil .fit(train_texts) dulu sebelum .transform().")
        tfidf_matrix = self._vectorizer.transform(texts.fillna(""))
        reduced = self._svd.transform(tfidf_matrix)
        cols = [f"tfidf_svd_{i}" for i in range(reduced.shape[1])]
        return pd.DataFrame(reduced, columns=cols, index=texts.index)

    @property
    def explained_variance_ratio_(self) -> np.ndarray:
        return self._svd.explained_variance_ratio_


# 5. Agregasi fitur level-artikel -> level-harian (join key: aligned_trading_date)
def aggregate_daily_features(
    article_df: pd.DataFrame,
    date_col: str = "aligned_trading_date",
) -> pd.DataFrame:
    sentiment_cols = [c for c in article_df.columns if c.startswith(("vader_", "lm_"))]
    svd_cols = [c for c in article_df.columns if c.startswith("tfidf_svd_")]
    mean_cols = sentiment_cols + svd_cols + (["gpr_density"] if "gpr_density" in article_df else [])

    agg_dict = {c: "mean" for c in mean_cols}
    if "gpr_hits" in article_df.columns:
        agg_dict["gpr_hits"] = "sum"

    daily = article_df.groupby(date_col).agg(agg_dict)
    daily["news_count"] = article_df.groupby(date_col).size()
    return daily.reset_index()

# 1.1 Fitur Sentimen(Vader + Loughran-McDonald)

In [29]:
news_feat = compute_vader_sentiment(news, text_col='text_lemmatized')
news_feat = compute_lm_sentiment(news_feat, text_col='text_lemmatized')

news_base = compute_vader_sentiment(news, text_col='lower_text')
news_base = compute_lm_sentiment(news_base, text_col='lower_text')

In [30]:
print(f"Jumlah baris feat: {len(news_feat)}")
news_feat[['title', 'vader_compound', 'lm_polarity', 'lm_subjectivity']].head(5)

# Hasil sentimen VADER
vader_feat_result = news_feat[
    [
        "title",
        "vader_neg",
        "vader_neu",
        "vader_pos",
        "vader_compound",
    ]
].copy()

Jumlah baris feat: 4336

In [31]:
vader_feat_result.head(5)

,title,vader_neg,vader_neu,vader_pos,vader_compound
0,Central banks are bringing gold reserves home asgeopoliticalrisks rise,0.055,0.803,0.142,0.9796
1,Oil rises 2% as White House says no US-Iran talks happening,0.145,0.740,0.116,-0.8074
2,Jamie Dimon says markets underestimate risks and he wouldn’t buy stocks or Treasurys at current ...,0.183,0.693,0.125,-0.9399
3,China’s super-rich fled Singapore. Now they want to come back,0.058,0.692,0.250,0.9991
4,‘Don’t get too comfortable’: Wall Street’s ‘fear gauge’ hits 2026 low — here’s why it’s ...,0.151,0.730,0.119,-0.8492

In [32]:
print(f"Jumlah baris lower: {len(news_base)}")
news_base[['title', 'vader_compound', 'lm_polarity', 'lm_subjectivity']].head(5)

# Hasil sentimen VADER
vader_base_result = news_base[
    [
        "title",
        "vader_neg",
        "vader_neu",
        "vader_pos",
        "vader_compound",
    ]
].copy()

vader_base_result.head(5)

Jumlah baris lower: 4336

,title,vader_neg,vader_neu,vader_pos,vader_compound
0,Central banks are bringing gold reserves home asgeopoliticalrisks rise,0.029,0.901,0.071,0.9631
1,Oil rises 2% as White House says no US-Iran talks happening,0.110,0.812,0.078,-0.9474
2,Jamie Dimon says markets underestimate risks and he wouldn’t buy stocks or Treasurys at current ...,0.097,0.819,0.084,0.3641
3,China’s super-rich fled Singapore. Now they want to come back,0.042,0.795,0.163,0.9991
4,‘Don’t get too comfortable’: Wall Street’s ‘fear gauge’ hits 2026 low — here’s why it’s ...,0.112,0.800,0.088,-0.8911

In [33]:
vader_base_result.head(5)

,title,vader_neg,vader_neu,vader_pos,vader_compound
0,Central banks are bringing gold reserves home asgeopoliticalrisks rise,0.029,0.901,0.071,0.9631
1,Oil rises 2% as White House says no US-Iran talks happening,0.110,0.812,0.078,-0.9474
2,Jamie Dimon says markets underestimate risks and he wouldn’t buy stocks or Treasurys at current ...,0.097,0.819,0.084,0.3641
3,China’s super-rich fled Singapore. Now they want to come back,0.042,0.795,0.163,0.9991
4,‘Don’t get too comfortable’: Wall Street’s ‘fear gauge’ hits 2026 low — here’s why it’s ...,0.112,0.800,0.088,-0.8911

In [34]:
comparison = pd.DataFrame({
    "title": news["title"],
    "vader_lower": news_base["vader_compound"],
    "vader_lemma": news_feat["vader_compound"],
    "lm_lower": news_base["lm_polarity"],
    "lm_lemma": news_feat["lm_polarity"],
})

comparison["vader_diff"] = comparison["vader_lower"] - comparison["vader_lemma"]
comparison["lm_diff"] = comparison["lm_lower"] - comparison["lm_lemma"]

comparison.head(5)

,title,vader_lower,vader_lemma,lm_lower,lm_lemma,vader_diff,lm_diff
0,Central banks are bringing gold reserves home asgeopoliticalrisks rise,0.9631,0.9796,-0.555555,-0.555555,-0.0165,0.000000
1,Oil rises 2% as White House says no US-Iran talks happening,-0.9474,-0.8074,-0.111111,-0.111111,-0.1400,0.000000
2,Jamie Dimon says markets underestimate risks and he wouldn’t buy stocks or Treasurys at current ...,0.3641,-0.9399,-0.461538,-0.538462,1.3040,0.076923
3,China’s super-rich fled Singapore. Now they want to come back,0.9991,0.9991,-0.150000,-0.150000,0.0000,0.000000
4,‘Don’t get too comfortable’: Wall Street’s ‘fear gauge’ hits 2026 low — here’s why it’s ...,-0.8911,-0.8492,-0.714286,-0.714286,-0.0419,0.000000

In [35]:
print("Perbedaan VADER:", (comparison["vader_diff"] != 0).sum())
print("Perbedaan LM   :", (comparison["lm_diff"] != 0).sum())

Perbedaan VADER: 4280
Perbedaan LM   : 2374

### Keputusan final sumber teks per lexicon

- **VADER -> `lower_text`**: VADER butuh negasi ("not"), intensifier ("very"), kapitalisasi, dan tanda baca yang hilang saat lemmatization/stopword removal.
- **LM -> `text_lemmatized`**: LM sudah menstem kata secara internal (bag-of-words), jadi cocok dipakai di teks yang sudah dinormalisasi, sejalan dengan `text_lemmatized` yang juga dipakai TF-IDF/SVD nantinya.

In [36]:
# Kombinasi final: VADER dari lower_text, LM dari text_lemmatized
news_feat = compute_vader_sentiment(news, text_col='lower_text')
news_feat = compute_lm_sentiment(news_feat, text_col='text_lemmatized')

print(f"Jumlah baris: {len(news_feat)}")
news_feat[['title', 'vader_compound', 'lm_polarity', 'lm_subjectivity']].head(5)

Jumlah baris: 4336

,title,vader_compound,lm_polarity,lm_subjectivity
0,Central banks are bringing gold reserves home asgeopoliticalrisks rise,0.9631,-0.555555,0.039474
1,Oil rises 2% as White House says no US-Iran talks happening,-0.9474,-0.111111,0.101887
2,Jamie Dimon says markets underestimate risks and he wouldn’t buy stocks or Treasurys at current ...,0.3641,-0.538462,0.104418
3,China’s super-rich fled Singapore. Now they want to come back,0.9991,-0.150000,0.096154
4,‘Don’t get too comfortable’: Wall Street’s ‘fear gauge’ hits 2026 low — here’s why it’s ...,-0.8911,-0.714286,0.083665

# 1.2 Indeks Resiko Geopolitik berbasis Keyword

In [37]:
news_feat = compute_gpr_density(news_feat, text_col='lower_text', keywords=DEFAULT_GPR_KEYWORDS)

print(news_feat['gpr_hits'].describe())
news_feat[['title', 'gpr_hits', 'gpr_density']].sort_values('gpr_density', ascending=False).head(5)

count    4336.000000
mean        2.711946
std         3.997439
min         0.000000
25%         0.000000
50%         1.000000
75%         3.000000
max        41.000000
Name: gpr_hits, dtype: float64

,title,gpr_hits,gpr_density
3818,"Emerging economies group BRICS invites 6 new members, including Saudi Arabia and Iran",32,0.035049
3652,"Oil steadies in choppy trading on tariff uncertainty, OPEC+ hike plans",17,0.031540
2756,OPEC+ to raise oil output slightly even as U.S.-Israel strikes on Iran disrupt shipments,14,0.030172
2285,An emboldened NATO provides a bittersweet moment for war-torn Ukraine,29,0.029502
1724,OPEC+ keeps oil output steady amid turmoil among members,13,0.029279

# 1.3 TF-IDF + SVD

In [38]:
extractor = TfidfSvdExtractor(max_features=5000, n_components=75, min_df=5)
extractor.fit(news_feat['text_lemmatized'])

svd_vec = extractor.transform(news_feat['text_lemmatized'])
news_feat = pd.concat([news_feat.reset_index(drop=True), svd_vec.reset_index(drop=True)], axis=1)

print(f"Explained variance ratio (kumulatif, {extractor.n_components} komponen): {extractor.explained_variance_ratio_.sum():.3f}")
svd_vec.head(3)

Explained variance ratio (kumulatif, 75 komponen): 0.237

,tfidf_svd_0,tfidf_svd_1,tfidf_svd_2,tfidf_svd_3,tfidf_svd_4,tfidf_svd_5,tfidf_svd_6,tfidf_svd_7,tfidf_svd_8,tfidf_svd_9,...,tfidf_svd_65,tfidf_svd_66,tfidf_svd_67,tfidf_svd_68,tfidf_svd_69,tfidf_svd_70,tfidf_svd_71,tfidf_svd_72,tfidf_svd_73,tfidf_svd_74
0,0.272386,0.130731,-0.060716,0.081283,-0.011045,-0.031668,-0.045758,-0.011606,-0.022026,-0.049104,...,-0.079944,-0.105850,0.020177,-0.112659,0.005519,0.085705,-0.042776,0.003524,-0.045443,-0.030497
1,0.340730,0.007782,0.270065,-0.044959,0.044673,0.062974,0.041566,0.118258,-0.002489,-0.011118,...,-0.029576,0.001795,-0.007135,-0.039125,-0.025280,-0.024280,0.023515,0.040962,-0.008034,-0.002545
2,0.296977,0.131154,-0.088787,0.032396,-0.042011,-0.037674,-0.037804,0.063501,0.000654,-0.034595,...,0.054777,-0.074153,-0.012344,0.020130,0.053371,0.052721,-0.003671,-0.008719,0.029853,0.039147

# 1.4 Agregaris ke Level Harian & Merge ke Data Kurs

daily_features = aggregate_daily_features(news_feat, date_col='aligned_trading_date')
print(f"Jumlah hari trading dengan fitur NLP: {len(daily_features)}")
daily_features.head(5)

In [39]:
daily_features = aggregate_daily_features(
    news_feat,
    date_col="aligned_trading_date",
)

print(f"Jumlah hari trading dengan fitur NLP: {len(daily_features)}")
daily_features.head()

Jumlah hari trading dengan fitur NLP: 1156

,aligned_trading_date,vader_neg,vader_neu,vader_pos,vader_compound,lm_positive,lm_negative,lm_polarity,lm_subjectivity,tfidf_svd_0,...,tfidf_svd_68,tfidf_svd_69,tfidf_svd_70,tfidf_svd_71,tfidf_svd_72,tfidf_svd_73,tfidf_svd_74,gpr_density,gpr_hits,news_count
0,2021-09-06,0.0700,0.881,0.04900,-0.9505,6.00,21.0,-0.555556,0.106299,0.303250,...,0.005938,-0.019196,-0.025434,0.074565,-0.001749,0.056623,-0.004710,0.000000,0,1
1,2021-09-08,0.0830,0.837,0.07900,-0.3395,11.00,43.0,-0.592593,0.142105,0.285621,...,0.024561,-0.027375,0.006369,0.008435,-0.034538,-0.048796,0.015683,0.001230,1,1
2,2021-09-09,0.0740,0.799,0.12700,0.9953,9.00,25.0,-0.470588,0.083744,0.312970,...,-0.004390,-0.003963,-0.013189,0.038953,0.011739,0.049731,-0.012375,0.006303,6,1
3,2021-09-10,0.0470,0.888,0.06500,0.8918,3.00,11.0,-0.571429,0.067308,0.278243,...,0.028025,0.036017,-0.008151,-0.009683,0.000592,0.004094,-0.050824,0.006612,4,1
4,2021-09-13,0.0965,0.825,0.07875,-0.0011,8.75,37.0,-0.595140,0.092247,0.304775,...,0.001062,-0.019711,0.001495,-0.049784,0.023224,0.047122,0.028836,0.001365,6,4

In [40]:
merged_data_v2 = pd.merge(
    bi_raw,
    daily_features,
    left_on='Tanggal_dt',
    right_on='aligned_trading_date',
    how='left',
)

print(f"Baris merged_data_v2: {len(merged_data_v2)}")
print(f"Hari tanpa berita (NaN fitur NLP): {merged_data_v2['news_count'].isna().sum()}")
merged_data_v2.head(5)

Baris merged_data_v2: 1202
Hari tanpa berita (NaN fitur NLP): 142

,NO,Nilai,Kurs Jual,Kurs Beli,Tanggal_dt,tanggal,jam,Tanggal,aligned_trading_date,vader_neg,...,tfidf_svd_68,tfidf_svd_69,tfidf_svd_70,tfidf_svd_71,tfidf_svd_72,tfidf_svd_73,tfidf_svd_74,gpr_density,gpr_hits,news_count
0,1,1,17834.73,17657.27,2026-09-01,09/01/2026,12:00 AM,2026-09-01,2026-09-01,0.157000,...,-0.015221,-0.024285,0.035738,-0.000381,0.030808,-0.005420,-0.010191,0.002008,1.0,1.0
1,2,1,17791.51,17614.49,2026-08-31,08/31/2026,12:00 AM,2026-08-31,2026-08-31,0.112000,...,0.001745,0.021222,-0.005325,-0.024874,0.018635,0.014870,0.013658,0.006466,43.0,7.0
2,3,1,17850.81,17673.19,2026-08-28,08/28/2026,12:00 AM,2026-08-28,2026-08-28,0.084333,...,0.019693,-0.006501,-0.020886,-0.015738,0.009945,0.008294,0.014060,0.008579,37.0,6.0
3,4,1,17805.58,17628.42,2026-08-27,08/27/2026,12:00 AM,2026-08-27,2026-08-27,0.110000,...,-0.039125,-0.025280,-0.024280,0.023515,0.040962,-0.008034,-0.002545,0.008432,5.0,1.0
4,5,1,17791.51,17614.49,2026-08-26,08/26/2026,12:00 AM,2026-08-26,2026-08-26,0.073000,...,0.007015,0.020591,-0.002135,0.024654,0.011187,0.004372,0.043154,0.004193,10.0,4.0

# 1.5 Sanity Check

In [41]:
check = merged_data_v2.sort_values('Tanggal_dt').copy()
check['kurs_next'] = check['Kurs Jual'].shift(-1)
check['kurs_change_next'] = check['kurs_next'] - check['Kurs Jual']

corr_cols = ['vader_compound', 'lm_polarity', 'gpr_density', 'gpr_hits', 'news_count', 'kurs_change_next']
check[corr_cols].corr()['kurs_change_next']

vader_compound     -0.047843
lm_polarity        -0.018804
gpr_density         0.045604
gpr_hits            0.054945
news_count          0.036842
kurs_change_next    1.000000
Name: kurs_change_next, dtype: float64